"use client";
import {useEffect,useRef} from "react";
import type {CSSProperties} from "react";
import {Plus} from "lucide-react";
import type {PadView,ActionPad} from "@/lib/engine/performance-state";

export default function ActionPads({pads,bank,onPress,onRelease,onEdit,disabled=false}:{pads:PadView[];bank:ActionPad["bank"];onPress:(id:string)=>void|Promise<void>;onRelease:(id:string)=>void|Promise<void>;onEdit?:(slot:number)=>void;disabled?:boolean}){
 const held=useRef(new Map<string,Promise<void>>()),handlers=useRef({onPress,onRelease});handlers.current={onPress,onRelease};
 function press(pad:PadView){if(held.current.has(pad.id)||disabled||!pad.ready)return;const promise=Promise.resolve().then(()=>handlers.current.onPress(pad.id)).then(()=>{});if(pad.trigger==="hold")held.current.set(pad.id,promise);void promise.catch(()=>{});}
 function release(id:string){const pending=held.current.get(id);if(!pending)return;held.current.delete(id);void Promise.resolve().then(()=>handlers.current.onRelease(id)).catch(()=>{});}
 useEffect(()=>{const drain=()=>{for(const id of held.current.keys())release(id);},visibility=()=>{if(document.visibilityState!=="visible")drain();};window.addEventListener("blur",drain);document.addEventListener("visibilitychange",visibility);return()=>{drain();window.removeEventListener("blur",drain);document.removeEventListener("visibilitychange",visibility);};},[]);
 useEffect(()=>{for(const id of held.current.keys())release(id);},[bank,disabled]);
 return <div className="action-pad-grid" role="group" aria-label={`Action bank ${bank}`}>{Array.from({length:12},(_,slot)=>{const pad=pads.find(p=>p.bank===bank&&p.slot===slot);return pad?<button key={pad.id} className={"action-pad "+(pad.active?"active":"")} style={{"--pad-color":pad.color} as CSSProperties} disabled={disabled||!pad.ready} aria-pressed={pad.trigger!=="tap"?pad.active:undefined} title={`${pad.label} · ${pad.trigger}${pad.ready?"":" · incompatible / missing asset"}`} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);press(pad);}} onPointerUp={()=>release(pad.id)} onPointerCancel={()=>release(pad.id)} onLostPointerCapture={()=>release(pad.id)} onKeyDown={e=>{if((e.key==="Enter"||e.code==="Space")&&!e.repeat){e.preventDefault();press(pad);}}} onKeyUp={e=>{if(e.key==="Enter"||e.code==="Space"){e.preventDefault();release(pad.id);}}} onClick={e=>{if(e.detail===0&&!held.current.has(pad.id)){press(pad);if(pad.trigger==="hold")release(pad.id);}}} onContextMenu={e=>{if(onEdit){e.preventDefault();onEdit(slot);}}}><span className="action-pad-slot">{String(slot+1).padStart(2,"0")}</span><strong>{pad.label}</strong><small>{pad.trigger==="hold"?"HOLD · 8s max":pad.trigger.toUpperCase()}</small></button>:<button key={`empty-${slot}`} className="action-pad empty-pad" disabled={!onEdit||disabled} onClick={()=>onEdit?.(slot)} aria-label={`Assign pad ${slot+1}`}><span className="action-pad-slot">{String(slot+1).padStart(2,"0")}</span><Plus size={16}/><small>ASSIGN</small></button>;})}</div>;
}
