"use client";
import {useEffect,useState} from "react";
import {Cloud,Cpu,Plus,Save,Trash2} from "lucide-react";
import type {Config,SavedCharacter} from "@/lib/engine/state";
import {RobotAppearance} from "./robot-controls";
export default function CharacterLibrary({value,robot,busy,onChange,onSave,onLoad,onDelete,onNew,onDownload}:{value:Config;robot:boolean;busy:boolean;onChange:(c:Config)=>void;onSave:(name:string,asNew:boolean)=>Promise<void>;onLoad:(p:SavedCharacter)=>void;onDelete:(id:string)=>void;onNew:()=>void;onDownload:()=>void}){
 const selected=value.characters.items.find(p=>p.id===value.characters.selected),[name,setName]=useState("My SGX character");useEffect(()=>{setName(selected?.name||"My SGX character");},[selected?.id,selected?.name]);
 return <div className="character-library"><div className="tab-heading"><h2>Build your cast.</h2><p>Save a character, switch looks, and return to its last pose or timeline. Your library reopens from your account.</p></div><div className="character-library-grid">{value.characters.items.map(p=><div key={p.id} className={p.id===selected?.id?"selected":""}><button disabled={busy} onClick={()=>onLoad(p)} aria-pressed={p.id===selected?.id}><span className="character-swatch" style={{background:p.robot.armor,borderColor:p.robot.eyes}}><Cpu size={22}/></span><strong>{p.name}</strong><small>{p.avatar.character==="sgx"?"SGX Robot":p.avatar.character.replaceAll("-"," ")} · {value.performance.clips.filter(c=>c.character===p.id).length} clips</small></button><button aria-label={`Delete ${p.name}`} disabled={busy} onClick={()=>onDelete(p.id)}><Trash2 size={13}/></button></div>)}</div><button className="full-button" disabled={busy} onClick={onNew}><Plus size={15}/>Start a fresh robot</button>
 <div className="character-save"><label className="field-label" htmlFor="character-name">Character name</label><input id="character-name" className="text-input" value={name} maxLength={60} onChange={e=>setName(e.target.value)}/><div className="settings-actions"><button className="gold-button" disabled={busy||!name.trim()||!selected} onClick={()=>void onSave(name,false)}><Save size={14}/>Save changes</button><button disabled={busy||!name.trim()||value.characters.items.length>=24} onClick={()=>void onSave(name,true)}><Cloud size={14}/>{selected?"Save as new":"Save character"}</button></div><p className="field-note">{value.characters.items.length} / 24 characters. Saving also keeps your poses, animation timeline and action deck in the cloud.</p></div>
 <div className="control-group"><h3>Overall transform</h3>{([["scale","Character scale",.1,3],["y","Height offset",-3,3],["yaw","Turn",-180,180]] as const).map(([key,label,min,max])=><label key={key} className="field-label">{label} <output>{value.avatar[key].toFixed(2)}</output><input className="pose-range" aria-label={label} type="range" min={min} max={max} step={key==="yaw"?1:.05} value={value.avatar[key]} onChange={e=>onChange({...value,avatar:{...value.avatar,[key]:e.target.valueAsNumber}})}/></label>)}</div>
 {robot?<RobotAppearance value={value.robot} onChange={r=>onChange({...value,robot:{...value.robot,...r}})} onDownload={onDownload}/>:<div className="control-group"><label className="color-control"><span>Character tint</span><input type="color" value={value.avatar.color} onChange={e=>onChange({...value,avatar:{...value.avatar,color:e.target.value,tint:true}})}/></label><p className="field-note">Imported rigs keep their authored geometry. Use Pose for joint transforms and Layers for pieces. Save keeps the model with your character.</p></div>}
 </div>;
}
