import {commandSchema,envelopeSchema,faceSchema,snapshotSchema,previewSchema,packFace,unpackFace,type CommandEnvelope,type FacePacket,type HostSnapshot,type Pairing,type RemoteCommand,type RemoteStatus,type PreviewFrame,type SessionView} from "./protocol";
import type {TrackingFrame} from "../engine/state";
export class RemoteError extends Error{constructor(message:string,public status=0){super(message);}}
export async function remoteRequest<T>(url:string,body:unknown,signal?:AbortSignal,credential?:string,method="POST"):Promise<T>{const response=await fetch(url,{method,headers:{"Content-Type":"application/json",...(credential?{"x-sgx-pair":credential}:{})},body:method==="DELETE"?undefined:JSON.stringify(body),cache:"no-store",signal:signal?AbortSignal.any([signal,AbortSignal.timeout(6000)]):AbortSignal.timeout(6000)});const data=await response.json() as T&{error?:string};if(!response.ok)throw new RemoteError(data.error||"No se pudo conectar con el estudio.",response.status);return data;}
const ICE_SERVERS:RTCIceServer[]=[{urls:"stun:stun.cloudflare.com:3478"}];
const delay=(ms:number,signal:AbortSignal,wake?:EventTarget)=>new Promise<void>(resolve=>{const finish=()=>{clearTimeout(timer);signal.removeEventListener("abort",finish);wake?.removeEventListener("wake",finish);resolve();};const timer=setTimeout(finish,ms);signal.addEventListener("abort",finish,{once:true});wake?.addEventListener("wake",finish,{once:true});if(signal.aborted)finish();});
async function gathered(pc:RTCPeerConnection,signal:AbortSignal){if(pc.iceGatheringState==="complete")return;await new Promise<void>(resolve=>{const finish=()=>{clearTimeout(timer);pc.removeEventListener("icegatheringstatechange",check);signal.removeEventListener("abort",finish);resolve();};const check=()=>{if(pc.iceGatheringState==="complete")finish();};const timer=setTimeout(finish,3500);pc.addEventListener("icegatheringstatechange",check);signal.addEventListener("abort",finish,{once:true});if(signal.aborted)finish();});}
abstract class Peer{
 protected life=new AbortController();protected pc?:RTCPeerConnection;protected face?:RTCDataChannel;protected control?:RTCDataChannel;protected previewChannel?:RTCDataChannel;protected generation=0;protected closed=false;protected terminalError="";
 protected pollWake=new EventTarget();
 protected get direct(){return this.pc?.connectionState==="connected"&&this.control?.readyState==="open"&&this.face?.readyState==="open";}
 protected wake(){this.pollWake.dispatchEvent(new Event("wake"));}
 protected closePeer(){++this.generation;this.control?.close();this.face?.close();this.previewChannel?.close();this.pc?.close();this.pc=undefined;this.face=undefined;this.control=undefined;this.previewChannel=undefined;}
 protected send(channel:RTCDataChannel|undefined,value:unknown){if(channel?.readyState!=="open"||channel.bufferedAmount>16384)return false;try{channel.send(JSON.stringify(value));return true;}catch{return false;}}
 protected parse(data:unknown){if(typeof data!=="string"||data.length>150000)return null;try{return JSON.parse(data);}catch{return null;}}
 dispose(){this.closed=true;this.life.abort();this.closePeer();}
}
export class RemoteHost extends Peer{
 private ack=0;private applied=new Map<string,{id:string;error?:string}>();private result?:HostSnapshot["result"];private offer?:{id:string;sdp:string};private activeOfferId="";private controllerId:string|null=null;private lastSeq=-1;private lastCamera=false;private lastSeen=0;private negotiating=false;private retryAt=0;private statusKey="";private expectedOrder=1;private ordered=new Map<number,CommandEnvelope>();private previewSeq=0;private previewFrame?:PreviewFrame;private previewEnabled=true;
 private constructor(public pairing:Pairing,private callbacks:{frame:(frame:TrackingFrame)=>void;snapshot:()=>HostSnapshot;command:(command:RemoteCommand)=>void;status:(status:RemoteStatus)=>void;preview?:()=>string|null}){super();}
 static async create(callbacks:RemoteHost["callbacks"]){const pair=await remoteRequest<Pairing>("/api/remote",{op:"create"}),host=new RemoteHost(pair,callbacks);void host.loop();void host.previewLoop();return host;}
 private status(error?:string,expired=false){if(this.closed)return;if(expired)this.terminalError=error||"La sesión terminó.";if(this.terminalError){expired=true;error=this.terminalError;}const connected=!expired&&Date.now()-this.lastSeen<15000,s:RemoteStatus={connected,transport:connected?(this.direct?"direct":"cloud"):"waiting",camera:connected&&this.lastCamera,error,expired},key=JSON.stringify(s);if(key!==this.statusKey){this.statusKey=key;this.callbacks.status(s);}}
 private receiveFace(input:unknown){const checked=faceSchema.safeParse(input);if(!checked.success||checked.data.seq<=this.lastSeq||this.terminalError)return;this.lastSeq=checked.data.seq;this.lastCamera=checked.data.camera;this.callbacks.frame(unpackFace(checked.data));this.status();}
 private snapshot(cloud=false):HostSnapshot{return {...this.callbacks.snapshot(),...(this.result?{result:this.result}:{}),results:[...this.applied.values()].slice(-64),...(cloud&&this.previewFrame?{preview:this.previewFrame}:{})};}
 private execute(input:unknown){
  const parsed=envelopeSchema.safeParse(input);if(!parsed.success||this.terminalError)return;const item=parsed.data;
  if(item.epoch&&item.epoch!==this.controllerId)return;
  const previous=this.applied.get(item.id);if(previous){this.send(this.control,{type:"ack",result:previous});return;}
  if(item.order!==undefined){if(item.order<this.expectedOrder)return;if(item.order>this.expectedOrder){if(this.ordered.size<48)this.ordered.set(item.order,item);return;}}
  let error:string|undefined;try{this.callbacks.command(item.command);}catch(e){error=(e instanceof Error?e.message:"El pad no se pudo aplicar.").slice(0,300);}
  this.result={id:item.id,...(error?{error}:{})};this.applied.set(item.id,this.result);if(this.applied.size>256)this.applied.delete(this.applied.keys().next().value!);
  this.send(this.control,{type:"ack",result:this.result});this.send(this.control,{type:"state",state:this.snapshot()});this.wake();
  if(item.order!==undefined){this.expectedOrder++;const next=this.ordered.get(this.expectedOrder);if(next){this.ordered.delete(this.expectedOrder);this.execute(next);}}
 }
 private async previewLoop(){while(!this.closed){if(this.callbacks.preview&&this.controllerId&&Date.now()-this.lastSeen<15000&&this.previewEnabled){
   // Preview has its own disposable channel. It cannot queue ahead of a pad.
   if(!this.direct||this.previewChannel?.readyState==="open"&&this.previewChannel.bufferedAmount<24000){try{const image=this.callbacks.preview();if(image){const frame={seq:++this.previewSeq,image};if(previewSchema.safeParse(frame).success){this.previewFrame=frame;if(this.direct)this.send(this.previewChannel,{type:"preview",frame});}}}catch{}}
  }await delay(this.direct?125:500,this.life.signal);}}
 private async negotiate(){if(this.negotiating||this.closed||!this.controllerId||typeof RTCPeerConnection==="undefined")return;this.negotiating=true;this.closePeer();this.activeOfferId="";const generation=this.generation;
  try{const pc=new RTCPeerConnection({iceServers:ICE_SERVERS});this.pc=pc;this.face=pc.createDataChannel("sgx-face",{ordered:false,maxRetransmits:0});this.control=pc.createDataChannel("sgx-control",{ordered:true});this.previewChannel=pc.createDataChannel("sgx-preview",{ordered:false,maxRetransmits:0});this.face.onmessage=e=>{if(generation===this.generation){this.lastSeen=Date.now();this.receiveFace(this.parse(e.data));}};this.control.onmessage=e=>{if(generation===this.generation){const value=this.parse(e.data);this.lastSeen=Date.now();if(value?.type==="command")this.execute(value.envelope);if(value?.type==="ping"&&Number.isFinite(value.time))this.send(this.control,{type:"pong",time:value.time});if(value?.type==="preview-enabled"&&typeof value.enabled==="boolean")this.previewEnabled=value.enabled;}};this.control.onopen=()=>{if(generation===this.generation){this.send(this.control,{type:"state",state:this.snapshot()});this.status();}};for(const channel of [this.face,this.control])channel.onclose=()=>{if(generation===this.generation){this.status();this.wake();}};pc.onconnectionstatechange=()=>{if(generation===this.generation){this.status();if(!this.direct)this.wake();}};await pc.setLocalDescription(await pc.createOffer());await gathered(pc,this.life.signal);if(generation!==this.generation||this.closed)return;this.offer={id:crypto.randomUUID(),sdp:pc.localDescription!.sdp};this.activeOfferId=this.offer.id;this.retryAt=Date.now()+16000;}catch{this.retryAt=Date.now()+20000;}finally{this.negotiating=false;}
 }
 private async loop(){while(!this.closed){try{const state=this.snapshot(!this.direct),offer=this.offer,view=await remoteRequest<SessionView>("/api/remote/"+this.pairing.id,{op:"host",state,ack:this.ack,...(offer?{offer}:{})},this.life.signal);if(this.closed)return;if(offer===this.offer)this.offer=undefined;this.lastSeen=Date.now()-(view.now-view.controllerSeen);
   if(view.controllerId!==this.controllerId){this.controllerId=view.controllerId;this.lastSeq=-1;this.lastCamera=false;this.expectedOrder=1;this.ordered.clear();this.applied.clear();this.result=undefined;this.previewEnabled=true;this.closePeer();this.retryAt=0;}
   if(this.controllerId&&!this.direct&&Date.now()>this.retryAt&&!this.negotiating)void this.negotiate();
   if(view.answer&&this.pc?.signalingState==="have-local-offer"&&view.answer.id===this.activeOfferId){try{await this.pc.setRemoteDescription({type:"answer",sdp:view.answer.sdp});}catch{this.retryAt=Date.now()+2000;}}
   if(view.frame&&view.now-view.frameUpdated<650)this.receiveFace(view.frame);for(const item of view.commands){this.execute({id:item.id,command:item.command,order:item.order,epoch:item.epoch});this.ack=Math.max(this.ack,item.seq);}this.send(this.control,{type:"state",state:this.snapshot()});this.status();
  }catch(e){if(this.closed)return;const expired=e instanceof RemoteError&&[401,403,410].includes(e.status);this.status(e instanceof Error?e.message:"Reconectando…",expired);if(expired){this.life.abort();this.closePeer();return;}}await delay(this.direct?1000:this.controllerId?100:800,this.life.signal,this.pollWake);}}
 async revoke(){const room=this.pairing.id;this.dispose();await remoteRequest("/api/remote/"+room,null,undefined,undefined,"DELETE");}
}
export type ControllerPair={id?:string;token?:string;code?:string};
export class RemoteController extends Peer{
 private seq=0;private latest?:FacePacket;private lastHttp=-1;private answer?:{id:string;sdp:string};private offerId="";private lastHost=0;private lastState?:HostSnapshot;private stateKey="";private statusKey="";private pending=new Map<string,{item:CommandEnvelope;started:number;posted:boolean;resolve:()=>void;reject:(error:Error)=>void;timer:ReturnType<typeof setTimeout>;fallback?:ReturnType<typeof setTimeout>}>();private commandOrder=0;private flushing=false;private rtt?:number;private previewSeq=-1;private previewEnabled=true;private lastPing=0;
 private constructor(public roomId:string,private credential:string,private controllerId:string,private callbacks:{state:(state:HostSnapshot)=>void;status:(status:RemoteStatus)=>void;preview?:(frame:PreviewFrame)=>void}){super();}
 static async connect(pair:ControllerPair,callbacks:RemoteController["callbacks"]){let key:string;try{const slot="sgx-controller:"+(pair.id||pair.code);key=sessionStorage.getItem(slot)||crypto.randomUUID();sessionStorage.setItem(slot,key);}catch{key=crypto.randomUUID();}const room=await remoteRequest<{id:string;controller:string}>("/api/remote",{op:"join",...pair,controller:key}),controller=new RemoteController(room.id,pair.token||pair.code!,room.controller,callbacks);void controller.loop();return controller;}
 private status(error?:string,expired=false){if(this.closed)return;if(expired)this.terminalError=error||"La sesión terminó.";if(this.terminalError){expired=true;error=this.terminalError;}const connected=!expired&&Date.now()-this.lastHost<15000,s:RemoteStatus={connected,transport:connected?(this.direct?"direct":"cloud"):"waiting",camera:!expired&&(this.latest?.camera??false),error,expired,rtt:this.rtt},key=JSON.stringify(s);if(key!==this.statusKey){this.statusKey=key;this.callbacks.status(s);}}
 private state(input:unknown){
  const parsed=snapshotSchema.safeParse(input);if(!parsed.success)return;this.lastState=parsed.data;
  const {preview,result,results,...visible}=parsed.data,key=JSON.stringify(visible);
  if(key!==this.stateKey){this.stateKey=key;this.callbacks.state(visible);}
  if(result)this.ack(result);for(const item of results||[])this.ack(item);if(preview)this.receivePreview(preview);
 }
 private ack(result:{id:string;error?:string}){const waiting=this.pending.get(result.id);if(!waiting)return;clearTimeout(waiting.timer);clearTimeout(waiting.fallback);this.rtt=Math.round(performance.now()-waiting.started);this.status();this.pending.delete(result.id);if(result.error)waiting.reject(new Error(result.error));else waiting.resolve();}
 sendFrame(frame:TrackingFrame,camera=true){if(this.closed||this.terminalError)return;this.latest=packFace(frame,++this.seq,camera);this.send(this.face,this.latest);}
 cameraOff(){this.sendFrame({signals:{},face:[],inference:0,time:0},false);this.status();}
 private receivePreview(input:unknown){const checked=previewSchema.safeParse(input);if(!checked.success||checked.data.seq<=this.previewSeq||!this.previewEnabled)return;this.previewSeq=checked.data.seq;this.callbacks.preview?.(checked.data);}
 setPreviewEnabled(enabled:boolean){this.previewEnabled=enabled;this.send(this.control,{type:"preview-enabled",enabled});}
 async command(command:RemoteCommand){
  commandSchema.parse(command);if(this.closed||this.terminalError||Date.now()-this.lastHost>15000||!this.lastState?.ready)throw new Error("El estudio no está listo. Mantén su pestaña abierta.");
  if(this.pending.size>=48)throw new Error("Hay demasiadas acciones pendientes. Revisa la conexión.");
  const item:CommandEnvelope={id:crypto.randomUUID(),command,order:++this.commandOrder,epoch:this.controllerId};
  return new Promise<void>((resolve,reject)=>{
   const timer=setTimeout(()=>{const message="El estudio no confirmó la acción. Vuelve a conectar el teléfono.";for(const pending of this.pending.values()){clearTimeout(pending.timer);clearTimeout(pending.fallback);pending.reject(new Error(message));}this.pending.clear();this.status(message,true);this.dispose();},10000);
   const p={item,started:performance.now(),posted:false,resolve,reject,timer,fallback:undefined as ReturnType<typeof setTimeout>|undefined};this.pending.set(item.id,p);
   if(this.direct&&this.send(this.control,{type:"command",envelope:item}))p.fallback=setTimeout(()=>{if(this.pending.has(item.id))void this.flushCloud();},400);
   else void this.flushCloud();
  });
 }
 private async flushCloud(){
  if(this.flushing||this.closed)return;this.flushing=true;
  try{while(!this.closed){const p=[...this.pending.values()].find(p=>!p.posted);if(!p)break;
   for(let attempt=0;attempt<2&&!this.closed;attempt++){try{await remoteRequest("/api/remote/"+this.roomId,{op:"command",controller:this.controllerId,...p.item},this.life.signal,this.credential);p.posted=true;this.wake();break;}catch(e){if(this.closed)return;if(!this.pending.has(p.item.id))break;if(attempt===0&&!(e instanceof RemoteError&&e.status>=400&&e.status<500)){await delay(300,this.life.signal);continue;}
    // A failed predecessor must not let a later release/toggle overtake it.
    for(const [id,pending] of this.pending){clearTimeout(pending.timer);clearTimeout(pending.fallback);pending.reject(e instanceof Error?e:new Error("No se pudo enviar la acción."));this.pending.delete(id);}this.terminalError="No se pudo entregar una acción. Vuelve a enlazar el teléfono.";this.status(this.terminalError,true);this.dispose();return;
   }}
  }}finally{this.flushing=false;}
 }
 private async negotiate(offer:{id:string;sdp:string}){if(this.closed||typeof RTCPeerConnection==="undefined"||offer.id===this.offerId)return;this.closePeer();this.offerId=offer.id;const generation=this.generation;try{const pc=new RTCPeerConnection({iceServers:ICE_SERVERS});this.pc=pc;pc.ondatachannel=e=>{if(generation!==this.generation){e.channel.close();return;}if(e.channel.label==="sgx-face")this.face=e.channel;if(e.channel.label==="sgx-preview"){this.previewChannel=e.channel;e.channel.onmessage=m=>{if(generation===this.generation){const value=this.parse(m.data);if(value?.type==="preview")this.receivePreview(value.frame);}};}if(e.channel.label==="sgx-control"){this.control=e.channel;e.channel.onmessage=m=>{if(generation!==this.generation)return;const value=this.parse(m.data);this.lastHost=Date.now();if(value?.type==="state")this.state(value.state);if(value?.type==="pong"&&Number.isFinite(value.time)){this.rtt=Math.round(Math.max(0,performance.now()-value.time));this.status();}if(value?.type==="ack"&&value.result&&typeof value.result.id==="string")this.ack(value.result);};}e.channel.onopen=()=>{if(generation===this.generation){this.setPreviewEnabled(this.previewEnabled);this.status();}};e.channel.onclose=()=>{if(generation===this.generation){this.status();this.wake();}};};pc.onconnectionstatechange=()=>{if(generation===this.generation){this.status();if(!this.direct)this.wake();}};await pc.setRemoteDescription({type:"offer",sdp:offer.sdp});await pc.setLocalDescription(await pc.createAnswer());await gathered(pc,this.life.signal);if(generation===this.generation&&!this.closed)this.answer={id:offer.id,sdp:pc.localDescription!.sdp};}catch{this.offerId="";}}
 private async loop(){while(!this.closed){try{if(this.direct&&performance.now()-this.lastPing>2000){this.lastPing=performance.now();this.send(this.control,{type:"ping",time:this.lastPing});}const frame=!this.direct&&this.latest&&this.latest.seq!==this.lastHttp?this.latest:undefined,answer=this.answer,view=await remoteRequest<SessionView>("/api/remote/"+this.roomId,{op:"controller",controller:this.controllerId,...(frame?{frame}:{}),...(answer?{answer}:{})},this.life.signal,this.credential);if(this.closed)return;if(frame)this.lastHttp=frame.seq;if(answer===this.answer)this.answer=undefined;this.lastHost=Date.now()-(view.now-view.hostSeen);if(view.state)this.state(view.state);if(view.offer&&view.offer.id!==this.offerId){this.answer=undefined;void this.negotiate(view.offer);}this.status();}catch(e){if(this.closed)return;const expired=e instanceof RemoteError&&[401,403,409,410].includes(e.status);this.status(e instanceof Error?e.message:"Reconectando…",expired);if(expired){this.cameraOff();this.closePeer();this.life.abort();return;}if(e instanceof RemoteError&&e.status===422){this.answer=undefined;this.offerId="";}}await delay(this.direct?1000:100,this.life.signal,this.pollWake);}}
 override dispose(){super.dispose();for(const p of this.pending.values()){clearTimeout(p.timer);clearTimeout(p.fallback);p.reject(new Error("El controlador se desconectó."));}this.pending.clear();}
 async leave(){const room=this.roomId,id=this.controllerId,credential=this.credential;this.dispose();await remoteRequest("/api/remote/"+room,{op:"leave",controller:id},undefined,credential);}
}
