"use client";
import {useEffect,useRef,useState} from "react";
import {Camera,CameraOff,Focus,Hand,Loader2,Pause,Play,Radio,RotateCcw,ScanFace,Smartphone,Unplug,Wifi,Zap} from "lucide-react";
import {CameraTracking,mediaProblem,type CameraStatus,type MediaProblem} from "@/lib/engine/tracking";
import {MODES} from "@/lib/engine/state";
import {trackingCoverage} from "@/lib/engine/rig";
import {ANIMATION_PRESETS,POWERS} from "@/lib/engine/highcoon";
import {RemoteController,RemoteError,type ControllerPair} from "@/lib/remote/client";
import {HAND_POSES,transportLabel,type HostSnapshot,type RemoteCommand,type RemoteStatus} from "@/lib/remote/protocol";
import ActionPads from "./action-pads";
import type {ActionPad} from "@/lib/engine/performance-state";
const poseLabels={none:"Liberar",open:"Abierta",fist:"Puño",point:"Señalar",spread:"Separar"};
export default function Controller(){
 const video=useRef<HTMLVideoElement>(null),tracker=useRef<CameraTracking|null>(null),remote=useRef<RemoteController|null>(null),generation=useRef(0),pairingBusy=useRef(false),lastFace=useRef(0),cameraStarting=useRef(false),wake=useRef<WakeLockSentinel|null>(null),sendingRef=useRef(false);
 const [code,setCode]=useState(""),[paired,setPaired]=useState(false),[connecting,setConnecting]=useState(false),[error,setError]=useState(""),[needsSignIn,setNeedsSignIn]=useState(false),[signIn,setSignIn]=useState("/signin-with-chatgpt?return_to=%2Fcontroller"),[status,setStatus]=useState<RemoteStatus>({connected:false,transport:"waiting",camera:false}),[state,setState]=useState<HostSnapshot|null>(null);
 const [camera,setCamera]=useState<CameraStatus>("off"),[progress,setProgress]=useState(""),[issue,setIssue]=useState<MediaProblem|null>(null),[face,setFace]=useState(false),[sending,setSending]=useState(false),[notice,setNotice]=useState(""),[side,setSide]=useState<"left"|"right"|"both">("both"),[clip,setClip]=useState(""),[loop,setLoop]=useState(false);
 const tracked=state?.tracking??{hands:true,body:"upper" as const};
 const options={hands:tracked.hands,pose:tracked.body!=="off",bodyMode:tracked.body==="full"?"full" as const:"upper" as const,rate:tracked.body!=="off"?20:tracked.hands?20:24};
 const optionsRef=useRef(options);optionsRef.current=options;
 const [coverage,setCoverage]=useState({hands:0,torso:false,arms:false,legs:false});
 const trackingMode=tracked.body!=="off"?tracked.body:tracked.hands?"hands":"face";
 useEffect(()=>{if(tracker.current?.stream)tracker.current.configure(optionsRef.current);},[options.hands,options.pose,options.bodyMode,options.rate]);
 const [bank,setBank]=useState<ActionPad["bank"]>("A"),[previewOn,setPreviewOn]=useState(true),[previewAge,setPreviewAge]=useState(Infinity),[cameraExpanded,setCameraExpanded]=useState(false);
 const previewEnabled=useRef(previewOn);previewEnabled.current=previewOn;
 const stagePreview=useRef<HTMLImageElement>(null),lastPreview=useRef(0),previewSource=useRef("");
 useEffect(()=>{const timer=setInterval(()=>setPreviewAge(lastPreview.current?Date.now()-lastPreview.current:Infinity),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{remote.current?.setPreviewEnabled(previewOn);if(stagePreview.current&&previewSource.current)stagePreview.current.src=previewSource.current;},[previewOn,paired]);
 function enqueue(command:RemoteCommand){const controller=remote.current;if(!controller)return Promise.reject(new Error("El controlador se desconectó."));return controller.command(command);}
 async function sendPad(id:string,phase:"press"|"release"){const label=state?.pads.find(p=>p.id===id)?.label||"Pad";try{await enqueue({type:"pad",id,phase});setError("");setNotice(label+(phase==="press"?" · aplicado":" · liberado"));if(phase==="press"&&"vibrate" in navigator)navigator.vibrate(15);}catch(e){setError(e instanceof Error?e.message:"El pad no se pudo enviar.");throw e;}}
 async function releaseWake(){const lock=wake.current;wake.current=null;try{await lock?.release();}catch{}}
 async function keepAwake(){try{if(document.visibilityState==="visible"&&tracker.current?.stream&&"wakeLock" in navigator)wake.current=await navigator.wakeLock.request("screen");}catch{}}
 async function connect(pair:ControllerPair){if(pairingBusy.current)return;pairingBusy.current=true;setConnecting(true);setError("");setNeedsSignIn(false);setNotice("");remote.current?.dispose();remote.current=null;tracker.current?.stop();setPaired(false);setState(null);lastPreview.current=0;previewSource.current="";setPreviewAge(Infinity);const ticket=++generation.current;
  try{const controller=await RemoteController.connect(pair,{state:setState,preview:frame=>{previewSource.current=frame.image;lastPreview.current=Date.now();if(stagePreview.current)stagePreview.current.src=frame.image;},status:s=>{setStatus(s);if(s.expired){tracker.current?.stop();void releaseWake();setError(s.error||"La sesión terminó.");setPaired(false);if(s.error?.includes("Sign in"))setNeedsSignIn(true);}}});if(ticket!==generation.current){controller.dispose();return;}remote.current=controller;controller.setPreviewEnabled(previewOn);setPaired(true);setNotice("Conectado. Activa la cámara o empieza con los pads.");}catch(e){if(ticket!==generation.current)return;setError(e instanceof Error?e.message:"No se pudo conectar.");setNeedsSignIn(e instanceof RemoteError&&e.status===401);}finally{if(ticket===generation.current){pairingBusy.current=false;setConnecting(false);}}
 }
 useEffect(()=>{if(video.current)tracker.current=new CameraTracking(video.current,frame=>{remote.current?.sendFrame(frame);if(performance.now()-lastFace.current>200){setFace(!!frame.face?.length);setCoverage(trackingCoverage(frame));lastFace.current=performance.now();}},(s,p)=>{setCamera(s);setProgress(p||"");if(s!=="on"){setFace(false);setCoverage({hands:0,torso:false,arms:false,legs:false});remote.current?.cameraOff();}if(s==="off")void releaseWake();},setIssue);
  const url=new URL(window.location.href);setSignIn("/signin-with-chatgpt?"+new URLSearchParams({return_to:url.pathname+url.hash}));const params=new URLSearchParams(url.hash.slice(1)),id=params.get("id"),token=params.get("token");if(id&&token&&/^[0-9a-f-]{36}$/.test(id)&&/^[a-f0-9]{64}$/.test(token))void connect({id,token});
  const visible=()=>{remote.current?.setPreviewEnabled(document.visibilityState==="visible"&&previewEnabled.current);if(document.visibilityState==="visible")void keepAwake();else setNotice("Mantén esta pantalla visible para continuar el tracking.");};document.addEventListener("visibilitychange",visible);return()=>{++generation.current;pairingBusy.current=false;remote.current?.dispose();tracker.current?.stop();void releaseWake();document.removeEventListener("visibilitychange",visible);};
 },[]);
 async function toggleCamera(){if(camera!=="off"){tracker.current?.stop();return;}if(!paired||cameraStarting.current)return;cameraStarting.current=true;setIssue(null);setError("");try{await enqueue({type:"tracking",hands:tracked.hands,body:tracked.body});await tracker.current?.start(optionsRef.current);await keepAwake();}catch(e){setIssue(mediaProblem(e));}finally{cameraStarting.current=false;}}
 async function send(command:RemoteCommand,label:string){if(!remote.current||sendingRef.current)return;sendingRef.current=true;setSending(true);setError("");setNotice("Enviando "+label+"…");try{await enqueue(command);setNotice(label+" · aplicado");if("vibrate" in navigator)navigator.vibrate(15);}catch(e){setError(e instanceof Error?e.message:"El pad no se pudo enviar.");setNotice("");}finally{sendingRef.current=false;setSending(false);}}
 async function disconnect(){tracker.current?.stop();const controller=remote.current;remote.current=null;setPaired(false);setState(null);setStatus({connected:false,transport:"waiting",camera:false});window.history.replaceState(null,"","/controller");setSignIn("/signin-with-chatgpt?return_to=%2Fcontroller");try{await controller?.leave();}catch(e){setError(e instanceof Error?e.message:"No se pudo cerrar la conexión.");}}
 const disabled=!paired||!status.connected||!state?.ready||sending,selectedHand=side==="both"?(state?.hands.left===state?.hands.right?state?.hands.left:null):state?.hands[side],chosenClip=state?.animations.includes(clip)?clip:state?.animations[0]||"";
 return <main className="controller" lang="es"><header className="controller-header"><a className="controller-brand" href="/" aria-label="Abrir estudio SGX"><b>SGX</b><span>REMOTE<br/><small>VTUBER ENGINE</small></span></a><div className={"controller-status "+(status.connected?"connected":"")}><Wifi size={16}/><span>{paired?transportLabel(status):"Controlador móvil"}</span></div></header><div className="controller-body">
  {!paired&&<section className="controller-pair"><Smartphone size={34}/><h1>Tu cara. Tus pads. Tu Highcoon.</h1><p>En el estudio, pulsa <strong>Conectar teléfono · QR</strong>. Escanea el QR o escribe aquí su código.</p><form onSubmit={e=>{e.preventDefault();void connect({code:code.replace(/\s|-/g,"").toUpperCase()});}}><label htmlFor="pair-code">Código de sesión</label><input id="pair-code" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9\s-]/g,"").slice(0,12))} autoCapitalize="characters" autoComplete="off" spellCheck={false} placeholder="ABCD EFGH" maxLength={12}/><button className="controller-primary" disabled={connecting||code.replace(/\s|-/g,"").length!==8}>{connecting?<Loader2 className="spin"/>:<Radio/>}{connecting?"Conectando…":"Conectar al estudio"}</button></form><p className="controller-note">Usa la misma cuenta de ChatGPT en los dos dispositivos. La computadora comparte su ventana limpia en Restream.</p></section>}
  {error&&<div className="controller-error" role="alert"><strong>{error}</strong>{needsSignIn&&<a href={signIn}>Entrar con ChatGPT y volver al controlador</a>}</div>}
  {paired&&status.error&&!status.expired&&<div className="controller-error" role="status"><strong>Reconectando al estudio…</strong><p>{status.error}</p></div>}
  {paired&&<div className="controller-model"><div><small>EN ESCENA</small><strong>{state?.model||"Conectando al personaje…"}</strong></div><button onClick={()=>void disconnect()} aria-label="Desconectar controlador"><Unplug size={18}/></button></div>}
  {paired&&<section className={"remote-stage-preview "+(!previewOn?"preview-collapsed":"")} aria-label="Live character monitor"><div className="remote-preview-heading"><strong>{state?.model||"Character"}</strong><span>{!previewOn?"PAUSADO":previewAge<2200?(status.transport==="direct"?"LIVE · 8 FPS":"NUBE · 2 FPS"):previewAge===Infinity?"PREPARANDO…":"FRAME ANTIGUO"}</span><button onClick={()=>{const next=!previewOn;setPreviewOn(next);remote.current?.setPreviewEnabled(next);}} aria-label={previewOn?"Ocultar preview del personaje":"Mostrar preview del personaje"}>{previewOn?"Ocultar":"Ver"}</button></div><img ref={stagePreview} alt="Preview en vivo de la salida del personaje" hidden={!previewOn}/>{previewOn&&previewAge===Infinity&&<p>El monitor aparecerá cuando el estudio esté listo.</p>}{state?.performance&&<div className="remote-preview-beat"><span>{state.performance.playing?"▶":"Ⅱ"} {state.performance.name}</span><output>{state.performance.time.toFixed(2)} / {state.performance.duration.toFixed(2)}s</output></div>}</section>}
  <section className={"controller-camera "+(paired&&!cameraExpanded?"camera-compact":"")}>
<div className="controller-section-title"><h2><ScanFace size={18}/>Tracking en vivo</h2>{paired&&<button onClick={()=>setCameraExpanded(v=>!v)}>{cameraExpanded?"Compactar":"Ampliar cámara"}</button>}<span>{camera==="on"?(face?"CARA DETECTADA":"BUSCANDO CARA"):camera==="off"?"CÁMARA APAGADA":"ABRIENDO CÁMARA"}</span></div><div className="controller-preview"><video ref={video} muted playsInline autoPlay className={camera==="off"?"hidden-video":""}/>{camera==="off"&&<div><ScanFace size={36}/><p>{paired?"Activa tu cámara o actúa con los pads":"Conecta el dispositivo para comenzar"}</p></div>}{camera!=="off"&&camera!=="on"&&<p className="controller-camera-progress">{progress||"Preparando tracking…"}</p>}</div><button className={camera==="off"?"controller-primary":""} onClick={()=>void toggleCamera()} disabled={!paired||!state?.ready}>{camera==="off"?<Camera size={19}/>:<CameraOff size={19}/>} {camera==="off"?"Activar cámara frontal":camera==="starting"?"Cancelar apertura":"Apagar cámara"}</button><div className="controller-tracking-modes" role="group" aria-label="Qué seguir con la cámara">{([["face","Cara · rápido"],["hands","Cara y dedos"],["upper","Manos y brazos"],["full","Cuerpo completo"]] as const).map(([mode,label])=><button key={mode} disabled={!paired||!state?.ready||sending||camera==="starting"||camera==="loading"} className={trackingMode===mode?"selected":""} aria-pressed={trackingMode===mode} onClick={()=>void send({type:"tracking",hands:mode!=="face",body:mode==="upper"||mode==="full"?mode:"off"},label)}>{label}</button>)}</div><div className="body-status" role="status">{tracked.hands&&<span className={coverage.hands?"found":""}>{coverage.hands}/2 manos</span>}{tracked.body!=="off"&&<span className={coverage.arms?"found":""}>Brazos {coverage.arms?"detectados":"esperando"}</span>}{tracked.body==="full"&&<span className={coverage.legs?"found":""}>Piernas {coverage.legs?"detectadas":"esperando"}</span>}</div><p className="controller-note">{trackingMode==="face"?"Cara prioriza velocidad; los pads dan movimiento al cuerpo.":trackingMode==="full"?"Coloca el teléfono de modo que vea hombros, manos, caderas y pies.":"Mantén hombros, codos y manos dentro de la cámara."} El video se queda en este dispositivo. Mantén esta pantalla visible.</p>{issue&&<div className="controller-error" role="alert"><strong>{issue.title}</strong><p>{issue.message}</p>{issue.standalone&&<a href={window.location.href} target="_blank" rel="noopener noreferrer">Abrir controlador en otra pestaña</a>}{tracker.current?.stream&&issue.kind==="tracking"&&<button onClick={()=>{setIssue(null);tracker.current?.retry(optionsRef.current);}}>Reintentar tracking</button>}</div>}</section>
  {paired&&<><div className="controller-command-status" role="status" aria-live="polite">{notice||(!state?.ready?"Esperando a que el personaje termine de cargar…":status.connected?"Pads listos":"Reconectando al estudio…")}</div>
   <section className="controller-section"><div className="controller-section-title"><h2>Action deck</h2><span>POSES / CLIPS / COMBOS</span></div><div className="deck-bank-tabs">{(["A","B","C"] as const).map(b=><button key={b} className={bank===b?"selected":""} aria-pressed={bank===b} onClick={()=>setBank(b)}>BANK {b}</button>)}</div><ActionPads pads={state?.pads||[]} bank={bank} disabled={disabled} onPress={id=>sendPad(id,"press")} onRelease={id=>sendPad(id,"release")}/><p className="controller-note">Directa envía al instante; Nube confirma después de recibir. Para conectar directo, mantén ambos dispositivos en la misma Wi-Fi. Configura los pads en la pestaña Pads del estudio. Tus poses y clips de keyframes aparecen aquí con sus nombres. Hold restaura al soltar; Toggle restaura al segundo toque.</p></section>
   <section className="controller-section"><div className="controller-section-title"><h2>Expresiones</h2><span>PERFORMANCE / 01</span></div><div className="controller-pad-grid">{MODES.map(mode=><button key={mode} className={state?.mode===mode?"selected":""} aria-pressed={state?.mode===mode} disabled={disabled} onClick={()=>void send({type:"mode",mode},mode)}><span>{mode}</span><small>{({NEUTRAL:"Natural",HYPE:"Energía",SERIOUS:"Serio",WTF:"Sorpresa",TERP:"Orgánico",TECH:"Wireframe"})[mode]}</small></button>)}</div></section>
   <section className="controller-section"><div className="controller-section-title"><h2>Movimientos</h2><span>{state?.animations.length||0} CLIPS</span></div><div className="controller-pad-grid">{ANIMATION_PRESETS.filter(p=>state?.animations.includes(p.name)).map(p=><button key={p.name} disabled={disabled} className={state?.animation===p.name?"selected":""} onClick={()=>void send({type:"animation",name:p.name,loop:p.loop},p.label)}><Play size={17}/><span>{p.label}</span></button>)}</div>{!!state?.animations.length&&<div className="controller-clip"><label htmlFor="clip">Todos los clips</label><select id="clip" value={chosenClip} onChange={e=>setClip(e.target.value)}>{state.animations.map(name=><option key={name}>{name}</option>)}</select><label className="controller-check"><input type="checkbox" checked={loop} onChange={e=>setLoop(e.target.checked)}/>Repetir en loop</label><button onClick={()=>void send({type:"animation",name:chosenClip,loop},chosenClip)} disabled={disabled}>Ejecutar clip</button></div>}{!state?.animations.length&&<p className="controller-note">Carga un Highcoon o un modelo con animaciones en el estudio.</p>}</section>
   <section className="controller-section"><div className="controller-section-title"><h2><Hand size={18}/>Manos de puppet</h2><span>POSES / 02</span></div><div className="controller-sides" role="group" aria-label="Mano del personaje">{(["left","both","right"] as const).map(s=><button key={s} aria-pressed={side===s} className={side===s?"selected":""} onClick={()=>setSide(s)}>{s==="left"?"Izquierda":s==="right"?"Derecha":"Ambas"}</button>)}</div><div className="controller-pad-grid">{HAND_POSES.map(pose=><button key={pose} aria-pressed={selectedHand===pose} className={selectedHand===pose?"selected":""} disabled={disabled} onClick={()=>void send({type:"hand",side,pose},poseLabels[pose])}><Hand size={18}/><span>{poseLabels[pose]}</span></button>)}</div><p className="controller-note">Izquierda y derecha corresponden al personaje. Liberar devuelve la mano a su animación o tracking.</p></section>
   <section className="controller-section"><div className="controller-section-title"><h2><Zap size={18}/>Powers</h2><span>TERP CHANNELS / 03</span></div><div className="controller-pad-grid power-pads">{POWERS.map(power=><button key={power.id} style={{borderTopColor:power.color}} disabled={disabled} className={state?.power===power.id?"selected":""} aria-pressed={state?.power===power.id} onClick={()=>void send({type:"power",id:power.id},power.name)}><small style={{color:power.color}}>{power.channel}</small><span>{power.name}</span></button>)}</div><div className="controller-tools"><button disabled={disabled} onClick={()=>void send({type:"power",id:"spectrum"},"Full Spectrum")}>Full Spectrum</button><button disabled={disabled||state?.power==="none"} onClick={()=>void send({type:"overload"},"Overload")}><Zap size={16}/>Overload · 8s</button><button disabled={disabled} onClick={()=>void send({type:"power",id:"none"},"Sin poderes")}>Apagar poderes</button></div></section>
   <section className="controller-section"><div className="controller-section-title"><h2>Control de escena</h2><span>DIRECTOR / 04</span></div><div className="controller-tools"><button disabled={disabled||!state?.face} onClick={()=>void send({type:"calibrate"},"Calibrar cara")}><Focus size={17}/>Calibrar cara</button><button disabled={disabled} onClick={()=>void send({type:"freeze",value:!state?.frozen},state?.frozen?"Continuar":"Pausar")}>{state?.frozen?<Play size={17}/>:<Pause size={17}/>} {state?.frozen?"Continuar":"Pausar personaje"}</button><button disabled={disabled} onClick={()=>void send({type:"camera",frame:"bust"},"Plano busto")}>Plano busto</button><button disabled={disabled} onClick={()=>void send({type:"camera",frame:"full"},"Cuerpo completo")}>Cuerpo completo</button><button disabled={disabled} onClick={()=>void send({type:"reset"},"Neutral")}><RotateCcw size={17}/>Volver a neutral</button></div></section>
  </>}<footer className="controller-footer">SPATIALGINEERS · SGX vTuber Engine<br/>Cara desde aquí. Escena y salida desde tu computadora.</footer>
 </div></main>;
}
