"use client";
import {useEffect,useRef,useState} from "react";
import * as T from "three";
import {Bone,Move3D,Pause,Play,Plus,Redo2,RotateCcw,Save,SkipBack,Trash2,Undo2} from "lucide-react";
import {toast} from "sonner";
import type {VtuberEngine} from "@/lib/engine/renderer";
import {keyAt,moveKey,retimeClip,mirrorFrame,snapTime,timelineGroup} from "@/lib/engine/timeline";
import {sampleClip} from "@/lib/engine/pose";
import {emptyFrame,nextNonce,performanceSchema,type Performance,type PoseFrame,type PoseClip} from "@/lib/engine/performance-state";

type Props={engine:VtuberEngine|null;value:Performance;onChange:(p:Performance)=>void;enabled:boolean;onEnabled:(v:boolean)=>void;autoKey?:boolean};
function error(e:unknown){return e instanceof Error?e.message:"Cannot update the performance library.";}
export function PoseWorkshop({engine,value,onChange,enabled,onEnabled,autoKey}:Props){
 const binding=engine?.poseBinding,editor=engine?.editor,ref=useRef(value),autoRef=useRef(autoKey);ref.current=value;autoRef.current=autoKey;
 const [selected,setSelected]=useState(""),[group,setGroup]=useState("all"),[mode,setMode]=useState<"translate"|"rotate"|"scale">("rotate"),[space,setSpace]=useState<"local"|"world">("local"),[snap,setSnap]=useState(false),[ik,setIK]=useState(true),[bones,setBones]=useState(true),[,setHistoryCount]=useState(0);
 const undo=useRef<PoseFrame[]>([]),redo=useRef<PoseFrame[]>([]);
 function commit(p:Performance){try{const parsed=performanceSchema.parse(p);ref.current=parsed;onChange(parsed);return true;}catch(e){toast.error(error(e));return false;}}
 function remember(){if(!binding)return;undo.current.push(binding.capture());if(undo.current.length>40)undo.current.shift();redo.current=[];setHistoryCount(n=>n+1);}
 function pose(frame:PoseFrame){if(!binding)return;const p=ref.current,time=p.playing?engine?.posePlayer.time??p.time:p.time,clip=p.clips.find(c=>c.id===p.clip&&c.model===binding.model);let clips=p.clips;if(autoRef.current&&clip){try{const next=keyAt(clip,time,frame,"smooth",clip.fps||30);clips=clips.map(c=>c.id===next.id?next:c);}catch(e){toast.error(error(e));return;}}onChange({...p,model:binding.model,mode:"pose",playing:false,time,frame,clips});}
 useEffect(()=>{if(!editor)return;undo.current=[];redo.current=[];setSelected(editor.selected);editor.onSelect=setSelected;editor.onStart=remember;editor.onChange=pose;return()=>{editor.onSelect=undefined;editor.onStart=undefined;editor.onChange=undefined;};},[editor]);
 useEffect(()=>{if(!editor)return;editor.setMode(mode);editor.setSpace(space);editor.setSnap(snap);editor.ik=ik;editor.showBones=bones;},[editor,mode,space,snap,ik,bones]);
 function enter(){if(!binding)return;remember();pose(binding.capture());engine?.frameCamera("full");onEnabled(true);}
 function restore(back:boolean){if(!binding)return;const from=back?undo.current:redo.current,to=back?redo.current:undo.current,frame=from.pop();if(frame){to.push(binding.capture());pose(frame);setHistoryCount(n=>n+1);}}
 const bone=binding?.byKey.get(selected),offset=bone&&binding?.offset(bone),euler=offset?new T.Euler().setFromQuaternion(new T.Quaternion().fromArray(offset.q),"XYZ"):new T.Euler();
 function numeric(kind:"p"|"q"|"s",axis:number,n:number){if(!bone||!binding||!Number.isFinite(n))return;remember();const frame=binding.capture(),v=binding.offset(bone);if(kind==="q"){const e=new T.Euler().setFromQuaternion(new T.Quaternion().fromArray(v.q),"XYZ");(["x","y","z"] as const).forEach((a,i)=>{if(i===axis)e[a]=T.MathUtils.degToRad(n);});v.q=new T.Quaternion().setFromEuler(e).toArray() as [number,number,number,number];}else v[kind][axis]=T.MathUtils.clamp(n,kind==="p"?-10000:.02,kind==="p"?10000:20);frame.bones[bone.key]=v;pose(frame);}
 const visible=binding?.bones.filter(b=>group==="all"||group==="face"&&b.face||group==="hands"&&/hand|thumb|index|middle|ring|little|finger/i.test(b.name)||group==="body"&&!b.face&&!/thumb|index|middle|ring|little|finger/i.test(b.name))||[];
  const joints=([ ["spine","Torso"],["leftHand","Mano izq."],["rightHand","Mano der."],["leftFoot","Pie izq."],["rightFoot","Pie der."] ] as const).map(([role,label])=>({label:String(label),node:editor?.rig?.joints.get(role)})).map(j=>({...j,bone:j.node&&binding?.byNode.get(j.node)}));joints.unshift({label:"Cabeza",node:binding?.bones.find(b=>/head/i.test(b.name))?.node,bone:binding?.bones.find(b=>/head/i.test(b.name))});
  return <div className="pose-workshop compact-workshop">
   {!enabled?<button className="full-button" disabled={!binding?.bones.length} onClick={enter}><Bone size={15}/>Seguir colocando el personaje</button>:<>
    <p className="field-note">Elige una parte y arrastra las flechas o los aros en el personaje. Las manos y los pies mueven también el brazo o la pierna.</p>
    <div className="quick-joints" aria-label="Parte del personaje">{joints.map(j=><button key={j.label} disabled={!j.bone} className={j.bone?.key===selected?"selected":""} aria-pressed={j.bone?.key===selected} onClick={()=>{if(j.bone){editor?.select(j.bone.key);setMode(editor?.canIK(j.bone.key)?"translate":"rotate");}}}>{j.label}</button>)}</div>
    <div className="pose-toolbar" role="group" aria-label="Cómo mover la parte">{(["translate","rotate","scale"] as const).map(m=><button key={m} className={mode===m?"selected":""} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m==="translate"?"Mover":m==="rotate"?"Girar":"Estirar"}</button>)}</div>
    <div className="pose-toolbar"><button disabled={!undo.current.length} onClick={()=>restore(true)}><Undo2 size={14}/>Deshacer</button><button disabled={!redo.current.length} onClick={()=>restore(false)}><Redo2 size={14}/>Rehacer</button><button disabled={!bone} onClick={()=>{if(!binding||!bone)return;remember();const frame=binding.capture();delete frame.bones[bone.key];pose(frame);}}><RotateCcw size={14}/>Restablecer parte</button></div>
    <details className="workflow-advanced"><summary>Todos los huesos y ajustes precisos</summary>
     <div className="pose-options"><label><input type="checkbox" checked={ik} onChange={e=>setIK(e.target.checked)}/>Mover extremidades juntas (IK)</label><label><input type="checkbox" checked={bones} onChange={e=>setBones(e.target.checked)}/>Mostrar huesos</label><label><input type="checkbox" checked={snap} onChange={e=>setSnap(e.target.checked)}/>Ajustar al grid</label><select aria-label="Gizmo space" value={space} onChange={e=>setSpace(e.target.value as typeof space)}><option value="local">Ejes de la parte</option><option value="world">Ejes de la escena</option></select></div>
     <div className="pose-toolbar bone-groups">{[["all","Todos"],["body","Cuerpo"],["hands","Manos"],["face","Cara"]].map(([g,label])=><button key={g} className={group===g?"selected":""} onClick={()=>setGroup(g)}>{label}</button>)}</div>
     <label className="field-label" htmlFor="pose-bone">Hueso · {binding?.bones.length||0} disponibles</label><select id="pose-bone" className="pose-select" value={selected} onChange={e=>editor?.select(e.target.value)}><option value="">Elige un hueso…</option>{selected&&!visible.some(b=>b.key===selected)&&bone&&<option value={selected}>{bone.name}</option>}{visible.map(b=><option key={b.key} value={b.key}>{b.name}</option>)}</select>
     {bone&&offset&&<div className="bone-numbers"><strong>{bone.name}</strong>{(["p","q","s"] as const).map(kind=><div key={kind}><span>{kind==="p"?"Posición":kind==="q"?"Grados":"Escala"}</span>{[0,1,2].map(axis=><label key={axis}>{"XYZ"[axis]}<input type="number" aria-label={`${bone.name} ${kind} ${"XYZ"[axis]}`} value={Number((kind==="q"?T.MathUtils.radToDeg(([euler.x,euler.y,euler.z])[axis]):offset[kind][axis]).toFixed(3))} step={kind==="q"?1:.01} onChange={e=>numeric(kind,axis,e.target.valueAsNumber)}/></label>)}</div>)}<small>Los campos usan los ejes locales del hueso.</small></div>}
     <button className="text-button" onClick={()=>{remember();pose(emptyFrame());}}>Restablecer toda la postura</button>
    </details>
   </>}
  </div>;
}

export function PoseTimeline({engine,value,onChange,time,character,autoKey=false,onAutoKey,onSave}:{engine:VtuberEngine|null;value:Performance;onChange:(p:Performance)=>void;time:number;character?:string;autoKey?:boolean;onAutoKey?:(v:boolean)=>void;onSave?:()=>void|Promise<void>}){
 const binding=engine?.poseBinding,[selectedKey,setSelectedKey]=useState(""),[easing,setEasing]=useState<"linear"|"smooth"|"step">("smooth"),[clock,setClock]=useState(time),[dragTime,setDragTime]=useState<number|null>(null),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState(""),[revision,setRevision]=useState(0);
 const ref=useRef(value);ref.current=value;const copied=useRef<{frame:PoseFrame;easing:typeof easing}|null>(null),history=useRef<{before:PoseClip[];after:PoseClip[]}[]>([]),historyIndex=useRef(0),drag=useRef<{id:string;left:number;width:number;time:number}|null>(null);
 const clips=value.clips.filter(c=>c.model===binding?.model),clip=clips.find(c=>c.id===value.clip),fps=clip?.fps||30,playhead=value.playing?clock:value.time;
 useEffect(()=>{if(!value.playing)return;const timer=setInterval(()=>setClock(engine?.posePlayer.time??time),50);return()=>clearInterval(timer);},[engine,value.playing,value.clip]);
 useEffect(()=>{history.current=[];historyIndex.current=0;},[binding]);
 async function save(){if(saving)return;setSaving(true);setSaveError("");try{await onSave?.();toast.success("Animación guardada en tu cuenta.");}catch(e){setSaveError(error(e));toast.error("No se pudo guardar la animación. Reintenta el guardado.");}finally{setSaving(false);}}
 function commit(p:Performance){try{const parsed=performanceSchema.parse(p);ref.current=parsed;onChange(parsed);return true;}catch(e){toast.error(error(e));return false;}}
 function remember(before:PoseClip[],after:PoseClip[]){history.current=history.current.slice(0,historyIndex.current);history.current.push({before,after});if(history.current.length>30)history.current.shift();historyIndex.current=history.current.length;setRevision(n=>n+1);}
 function update(c:PoseClip){const p=ref.current,next=p.clips.map(x=>x.id===c.id?c:x);if(commit({...p,clips:next}))remember(p.clips,next);}
 function undo(forward=false){const n=historyIndex.current+(forward?1:-1),item=history.current[forward?historyIndex.current:n];if(item&&commit({...ref.current,clips:forward?item.after:item.before,playing:false})){historyIndex.current=n;setRevision(r=>r+1);}}
 function seek(n:number){if(!clip)return;const t=snapTime(n,clip.duration,fps);onChange({...ref.current,model:clip.model,mode:"clip",clip:clip.id,time:t,playing:false,frame:sampleClip(clip,t),nonce:nextNonce(ref.current.nonce)});}
 function capture(frame=binding?.capture(),ease=easing){if(!clip||!frame)return;try{const c=keyAt(clip,playhead,frame,ease,fps);update(c);setSelectedKey(c.keyframes.find(k=>Math.abs(k.time-playhead)<1/fps)?.id||"");}catch(e){toast.error(error(e));}}
 const k=clip?.keyframes.find(k=>k.id===selectedKey),canCapture=!saving&&!value.playing&&!!binding;
 function cloneClip(){if(!clip)return;const c={...clip,id:crypto.randomUUID(),name:(clip.name+" copy").slice(0,60),character,keyframes:clip.keyframes.map(k=>({...k,id:crypto.randomUUID()}))};commit({...value,clip:c.id,playing:false,time:0,clips:[...value.clips,c]});setSelectedKey("");}
 function moveSelected(n:number){if(!clip||!k)return;try{const c=moveKey(clip,k.id,n,fps);update(c);}catch(e){toast.error(error(e));}}
 const groups=["Torso","Arms","Hands","Legs","Face"],animated=binding?.bones.filter(b=>clip?.keyframes.some(k=>k.frame.bones[b.key]))||[];
 return <section className="pose-timeline" aria-label="Pose animation timeline" data-revision={revision}>
  <div className="timeline-heading"><strong><Move3D size={15}/>TIMELINE AVANZADO</strong><button onClick={()=>void save()} disabled={saving||!clip}><Save size={14}/>{saving?"Guardando…":"Guardar animación"}</button></div>
  {saveError&&<p role="alert">No se pudo guardar. Los cambios siguen aquí. {saveError}</p>}
  {clip?<>
   <div className="timeline-controls"><button aria-label="Rewind animation" onClick={()=>seek(0)}><SkipBack size={15}/></button><button aria-label="Previous frame" onClick={()=>seek(playhead-1/fps)}>−1f</button><button aria-label="Play or pause animation" onClick={()=>onChange({...value,mode:"clip",model:clip.model,time:value.playing?(engine?.posePlayer.time??time):playhead>=clip.duration?0:playhead,playing:!value.playing,nonce:nextNonce(value.nonce)})}>{value.playing?<Pause size={15}/>:<Play size={15}/>}</button><button aria-label="Next frame" onClick={()=>seek(playhead+1/fps)}>+1f</button><output>{playhead.toFixed(2)} / {clip.duration.toFixed(2)}s · f{Math.round(playhead*fps)}</output><label><input type="checkbox" checked={value.loop} onChange={e=>onChange({...value,loop:e.target.checked})}/>Loop</label><select aria-label="Playback speed" value={value.speed} onChange={e=>onChange({...value,time:playhead,speed:Number(e.target.value),nonce:nextNonce(value.nonce)})}>{[.25,.5,1,1.5,2,3].map(v=><option key={v} value={v}>{v}x</option>)}</select><label className={autoKey?"auto-key-on":""}><input type="checkbox" checked={autoKey} onChange={e=>onAutoKey?.(e.target.checked)}/>Auto key</label><button className="gold-button" onClick={()=>capture()} disabled={!canCapture}><Plus size={14}/>Key whole rig</button></div>
   <input className="timeline-scrub" aria-label="Animation playhead" type="range" min={0} max={clip.duration} step={1/fps} value={Math.min(clip.duration,playhead)} onChange={e=>seek(e.target.valueAsNumber)}/>
   <div className="timeline-ruler">{Array.from({length:9},(_,i)=><span key={i}>{(clip.duration*i/8).toFixed(1)}s</span>)}</div>
   <div className="timeline-track" role="group" aria-label="Keyframes">{clip.keyframes.map(key=><button key={key.id} className={selectedKey===key.id?"selected":""} style={{left:`${(drag?.current?.id===key.id&&dragTime!==null?dragTime:key.time)/clip.duration*100}%`}} title={`${key.time.toFixed(2)}s · ${key.easing} · drag to move`} aria-label={`Keyframe at ${key.time.toFixed(2)} seconds`} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();const rect=e.currentTarget.parentElement!.getBoundingClientRect();drag.current={id:key.id,left:rect.left,width:rect.width,time:key.time};setSelectedKey(key.id);setEasing(key.easing);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(!d)return;d.time=snapTime((e.clientX-d.left)/d.width*clip.duration,clip.duration,fps);setDragTime(d.time);}} onPointerUp={()=>{const d=drag.current;drag.current=null;setDragTime(null);if(d){try{const c=moveKey(clip,d.id,d.time,fps);update(c);seek(d.time);}catch(e){toast.error(error(e));}}}} onPointerCancel={()=>{drag.current=null;setDragTime(null);}} onClick={e=>{if(e.detail===0){setSelectedKey(key.id);setEasing(key.easing);seek(key.time);}}}>◆</button>)}<span className="timeline-playhead" style={{left:`${Math.min(1,playhead/clip.duration)*100}%`}}/></div>
   <details className="timeline-channels"><summary>{animated.length} animated joints · body / hands / face tracks</summary>{groups.map(group=><div className="timeline-channel" key={group}><span>{group} · {animated.filter(b=>timelineGroup(b.name)===group).length}</span><div>{clip.keyframes.map(key=>Object.keys(key.frame.bones).some(id=>timelineGroup(binding?.byKey.get(id)?.name||id)===group)&&<button key={key.id} style={{left:`${key.time/clip.duration*100}%`}} aria-label={`${group} key at ${key.time.toFixed(2)}`} onClick={()=>{setSelectedKey(key.id);seek(key.time);}}>◆</button>)}</div></div>)}</details>
   <div className="timeline-details"><input aria-label="Clip name" value={clip.name} maxLength={60} onChange={e=>{if(e.target.value.trim())update({...clip,name:e.target.value});}}/><label>Duration<input aria-label="Clip duration" type="number" min={.1} max={300} step={.1} value={clip.duration} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber)){try{update(retimeClip(clip,e.target.valueAsNumber));}catch(err){toast.error(error(err));}}}}/></label><select aria-label="Timeline frame rate" value={fps} onChange={e=>update({...clip,fps:Number(e.target.value) as 24|30|60})}>{[24,30,60].map(v=><option key={v} value={v}>{v} fps</option>)}</select><select aria-label="Keyframe interpolation" value={easing} onChange={e=>{const ease=e.target.value as typeof easing;setEasing(ease);if(k)update({...clip,keyframes:clip.keyframes.map(x=>x.id===k.id?{...x,easing:ease}:x)});}}><option value="smooth">Smooth</option><option value="linear">Linear</option><option value="step">Hold / step</option></select>{k&&<><label>Key time<input aria-label="Selected keyframe time" type="number" min={0} max={clip.duration} step={1/fps} value={k.time} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))moveSelected(e.target.valueAsNumber);}}/></label><button disabled={clip.keyframes.length===1} onClick={()=>{update({...clip,keyframes:clip.keyframes.filter(x=>x.id!==k.id)});setSelectedKey("");}} title="Delete selected keyframe"><Trash2 size={14}/></button></>}</div>
   <div className="timeline-controls"><button disabled={!k} onClick={()=>{if(k){copied.current={frame:structuredClone(k.frame),easing:k.easing};setRevision(n=>n+1);}}}>Copy key</button><button disabled={!copied.current||!canCapture} onClick={()=>{if(copied.current)capture(structuredClone(copied.current.frame),copied.current.easing);}}>Paste at playhead</button><button disabled={!k||value.playing} onClick={()=>{if(k){update({...clip,keyframes:clip.keyframes.map(x=>x.id===k.id?{...x,frame:mirrorFrame(x.frame)}:x)});seek(k.time);}}}>Mirror key</button><button disabled={value.clips.length>=24} onClick={cloneClip}>Duplicate clip</button><button disabled={!historyIndex.current} onClick={()=>undo()}><Undo2 size={14}/>Undo</button><button disabled={historyIndex.current>=history.current.length} onClick={()=>undo(true)}><Redo2 size={14}/>Redo</button><button title="Delete this custom clip" onClick={()=>{commit({...value,mode:"pose",playing:false,clip:"",frame:binding?.capture()||value.frame,clips:value.clips.filter(c=>c.id!==clip.id),pads:value.pads.map(p=>p.action.clip===clip.id?{...p,action:{...p.action,clip:undefined}}:p)});setSelectedKey("");}}><Trash2 size={14}/>Clip</button></div>
   <p>Mueve el tiempo, coloca el personaje y pulsa Key whole rig. Auto key guarda cada ajuste. Arrastra los rombos para cambiar los tiempos; Duration estira toda la animación. Guardar animación conserva los cambios en tu cuenta. {clip.keyframes.length} / 120 keys.</p>
  </>:<p>Crea o abre una animación desde Crear para editar sus tiempos aquí.</p>}
 </section>;
}
