"use client";
import {useState} from "react";
import {QRCodeSVG} from "qrcode.react";
import {Copy,Smartphone,Unplug,Wifi} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "./ui/dialog";
import {transportLabel,type Pairing,type RemoteStatus} from "@/lib/remote/protocol";
export default function RemoteLink({pair,status,busy,onConnect,onDisconnect}:{pair:Pairing|null;status:RemoteStatus;busy:boolean;onConnect:()=>void;onDisconnect:()=>void}){const [open,setOpen]=useState(false),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false),url=pair&&typeof window!=="undefined"?new URL("/controller",window.location.origin).href+"#"+new URLSearchParams({id:pair.id,token:pair.token}):"";
 async function copy(){try{await navigator.clipboard.writeText(url);setCopied(true);setCopyError(false);setTimeout(()=>setCopied(false),2500);}catch{setCopyError(true);}}
 return <><button className={"remote-connect "+(pair?"selected":"")} onClick={()=>{setOpen(true);if(!pair)onConnect();}} disabled={busy}><Smartphone size={17}/><span>{busy?"Conectando…":pair?transportLabel(status):"Conectar teléfono · QR"}</span></button>{pair&&<p className="remote-inline-status" role="status"><Wifi size={12}/>{status.expired?"Sesión finalizada":status.camera?"Cámara remota activa":"Pads listos · cámara local libre"}</p>}<Dialog open={open} onOpenChange={setOpen}><DialogContent className="sgx-dialog remote-dialog"><DialogTitle>Cámara y pads en otro dispositivo</DialogTitle><DialogDescription>Comparte la ventana limpia en Restream. El teléfono controla la cara y los movimientos de Highcoon.</DialogDescription>{pair&&!status.expired?<><div className="remote-qr"><QRCodeSVG value={url} size={224} level="M" marginSize={3} title="Conectar controlador SGX"/></div><p className="remote-pair-code"><span>CÓDIGO DE SESIÓN</span><strong>{pair.code.slice(0,4)} {pair.code.slice(4)}</strong></p><p className="field-note">Escanea el QR o abre <a href="/controller" target="_blank" rel="noopener noreferrer">el controlador</a> y escribe el código. Usa la misma cuenta de ChatGPT en ambos dispositivos. Mantén las dos pestañas abiertas.</p><p className="remote-pair-state" role="status">{transportLabel(status)}{status.camera?" · cámara activa":""}</p><button className="full-button" onClick={()=>void copy()}><Copy size={16}/>{copied?"Enlace copiado":"Copiar enlace"}</button>{copyError&&<input className="remote-url" aria-label="Enlace del controlador" readOnly value={url} onFocus={e=>e.target.select()}/>}<p className="field-note">El video se queda en el teléfono; enviamos expresiones y comandos. El enlace vence en 6 horas.</p><button className="full-button" onClick={onDisconnect} disabled={busy}><Unplug size={16}/>Cerrar conexión y revocar QR</button></>:<><p role="status">{busy?"Creando tu sesión…":status.error||"Crea una nueva conexión."}</p><button className="full-button gold-button" onClick={onConnect} disabled={busy}>Crear conexión</button>{pair&&<button className="full-button" onClick={onDisconnect}>Liberar cámara local</button>}</>}{status.error&&pair&&!status.expired&&<p className="remote-error" role="alert">{status.error}</p>}</DialogContent></Dialog></>;
}
