"use client";
import {Cpu,RotateCcw,Download} from "lucide-react";
import {Slider} from "@/components/ui/slider";
import {Switch} from "@/components/ui/switch";
import {robotDefaults,type Config} from "@/lib/engine/state";
type Robot=Config["robot"];
function Range({label,value,onChange,min=0,max=2,step=.05,suffix="x"}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number;step?:number;suffix?:string}){return <div className="range-control"><div><label>{label}</label><output>{value.toFixed(step===1?0:2)}{suffix}</output></div><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(v[0])}/></div>;}
export function RobotAppearance({value,onChange,onDownload}:{value:Robot;onChange:(r:Partial<Robot>)=>void;onDownload:()=>void}){
  return <div className="control-group robot-customizer"><h3><Cpu size={16}/>SGX Robot · Customizer</h3><p className="field-note">Your original energy face. Colors, proportions and removable parts.</p>
    {([["armor","Armor / helmet"],["metal","Metal panels"],["dark","Body / face"],["eyes","Energy eyes"],["mouth","Energy mouth"],["energy","Core / accessories"]] as const).map(([key,label])=><label className="color-control" key={key}><span>{label}</span><span className="color-value">{value[key].toUpperCase()}<input type="color" aria-label={label} value={value[key]} onChange={e=>onChange({[key]:e.target.value})}/></span></label>)}
    <Range label="Eye glow" value={value.eyeGlow} max={4} onChange={eyeGlow=>onChange({eyeGlow})}/><Range label="Mouth glow" value={value.mouthGlow} max={4} onChange={mouthGlow=>onChange({mouthGlow})}/><Range label="Core glow" value={value.energyGlow} max={4} onChange={energyGlow=>onChange({energyGlow})}/>
    <div className="robot-piece-selects">{([["headStyle","Head shell",["classic","round","box"]],["eyeStyle","Energy eyes",["bar","round","diamond"]],["antennaStyle","Head pieces",["antenna","horns","ears"]]] as const).map(([key,label,options])=><label key={key}>{label}<select aria-label={label} value={value[key]} onChange={e=>onChange({[key]:e.target.value})}>{options.map(v=><option key={v} value={v}>{v}</option>)}</select></label>)}</div>
    <details className="robot-options" open><summary>Body proportions</summary>{([["armLength","Arm length"],["armWidth","Arm width"],["legLength","Leg length"],["legWidth","Leg width"],["handSize","Hand size"],["handWidth","Hand width"],["footSize","Foot size"],["bodyWidth","Body width"],["bodyHeight","Body height"],["shoulderWidth","Shoulder width"],["hipWidth","Hip width"]] as const).map(([key,label])=><Range key={key} label={label} value={value[key]} min={.5} max={2} onChange={n=>onChange({[key]:n})}/>)}</details>
    <details className="robot-options"><summary>Shape & surface</summary><Range label="Head size" value={value.headScale} min={.5} onChange={headScale=>onChange({headScale})}/><Range label="Eye width" value={value.eyeWidth} min={.5} onChange={eyeWidth=>onChange({eyeWidth})}/><Range label="Eye height" value={value.eyeHeight} min={.5} onChange={eyeHeight=>onChange({eyeHeight})}/><Range label="Mouth width" value={value.mouthWidth} min={.5} onChange={mouthWidth=>onChange({mouthWidth})}/><Range label="Jaw motion" value={value.jawMotion} onChange={jawMotion=>onChange({jawMotion})}/><Range label="Metalness" value={value.metalness} max={1} suffix="" onChange={metalness=>onChange({metalness})}/><Range label="Surface roughness" value={value.roughness} min={.2} max={3} onChange={roughness=>onChange({roughness})}/></details>
    <div className="robot-parts">{([["helmet","Helmet"],["antenna","Antennas"],["halo","Energy halo"],["sigil","Chest sigil"]] as const).map(([key,label])=><label className="toggle-control" key={key}><span>{label}</span><Switch aria-label={label} checked={value[key]} onCheckedChange={checked=>onChange({[key]:checked})}/></label>)}</div>
    <button className="full-button" onClick={()=>onChange({...robotDefaults(),pose:value.pose})}><RotateCcw size={15}/>Restore original look</button><button className="full-button" onClick={onDownload}><Download size={15}/>Download robot GLB</button><p className="field-note">Save keeps these controls, your layers and bone pose with the scene.</p>
  </div>;
}
