import {z} from "zod";
import {CloudError} from "../cloud-error";
import {envelopeSchema,faceSchema,snapshotSchema,type Pairing,type SessionView} from "./protocol";
const HOURS=21600000,LEASE=15000,id=z.string().uuid(),token=z.string().regex(/^[a-f0-9]{64}$/),sdp=z.string().min(1).max(120000);
export const operationSchema=z.discriminatedUnion("op",[
 z.object({op:z.literal("join"),code:z.string().regex(/^[A-Z2-9]{8}$/).optional(),id:id.optional(),token:token.optional(),controller:id}).strict(),
 z.object({op:z.literal("host"),state:snapshotSchema,ack:z.number().int().nonnegative(),offer:z.object({id:id,sdp}).optional()}).strict(),
 z.object({op:z.literal("controller"),controller:id,answer:z.object({id:id,sdp}).optional(),frame:faceSchema.optional()}).strict(),
 z.object({op:z.literal("command"),controller:id,...envelopeSchema.shape}).strict(),z.object({op:z.literal("leave"),controller:id}).strict(),
]);
type Operation=z.infer<typeof operationSchema>;
type Room={id:string;owner:string;join_hash:string;code:string;expires:number;host_seen:number;controller_seen:number;controller_id:string|null;controller_key:string|null;face_json:string|null;face_seq:number;face_updated:number;state_json:string|null;offer_json:string|null;answer_json:string|null;acked:number};
export async function hashToken(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join("");}
const secret=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,"0")).join("");
const parse=<T>(value:string|null):T|null=>value?JSON.parse(value) as T:null;
export class RemoteStore{
 constructor(private db:D1Database,private clock:()=>number=Date.now){}
 async create(owner:string):Promise<Pairing>{const now=this.clock(),room=crypto.randomUUID(),joinToken=secret(),alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",code=Array.from(crypto.getRandomValues(new Uint8Array(8)),b=>alphabet[b%32]).join("");
  await this.db.batch([this.db.prepare("DELETE FROM remote_commands WHERE created<? OR room IN (SELECT id FROM remote_rooms WHERE expires<?)").bind(now-30000,now),this.db.prepare("DELETE FROM remote_rooms WHERE expires<?").bind(now),this.db.prepare("INSERT INTO remote_rooms (id,owner,join_hash,code,expires,host_seen,controller_seen,face_seq,face_updated,acked) VALUES (?,?,?,?,?,?,0,-1,0,0)").bind(room,owner,await hashToken(joinToken),code,now+HOURS,now)]);return {id:room,token:joinToken,code,expires:now+HOURS};
 }
 async room(owner:string,roomId:string,joinToken?:string):Promise<Room>{if(!id.safeParse(roomId).success)throw new CloudError("Identificador de sesión no válido.");const room=await this.db.prepare("SELECT * FROM remote_rooms WHERE id=? AND owner=?").bind(roomId,owner).first<Room>();if(!room||room.expires<=this.clock())throw new CloudError("La sesión terminó. Crea una conexión nueva en el estudio.",410);if(joinToken&&(!token.safeParse(joinToken).success||await hashToken(joinToken)!==room.join_hash))throw new CloudError("El enlace de conexión no es válido.",403);return room;}
 private controller(room:Room,controllerId:string){if(room.controller_id!==controllerId)throw new CloudError("Otro controlador está conectado. Vuelve a enlazar este dispositivo.",409);}
 async join(owner:string,input:Extract<Operation,{op:"join"}>){const now=this.clock();let room:Room;if(input.id&&input.token)room=await this.room(owner,input.id,input.token);else if(input.code){const found=await this.db.prepare("SELECT * FROM remote_rooms WHERE owner=? AND code=? AND expires>? ORDER BY host_seen DESC LIMIT 1").bind(owner,input.code,now).first<Room>();if(!found)throw new CloudError("Código no encontrado. Comprueba el código del estudio.",404);room=found;}else throw new CloudError("Escanea el QR o escribe el código del estudio.");
  if(now-room.host_seen>LEASE)throw new CloudError("El estudio no responde. Mantén su pestaña abierta.",409);
  const lease=crypto.randomUUID();const result=await this.db.prepare("UPDATE remote_rooms SET controller_id=?,controller_key=?,controller_seen=?,face_seq=-1,face_json=NULL,answer_json=NULL WHERE id=? AND (controller_id IS NULL OR controller_key=? OR controller_seen<?)").bind(lease,input.controller,now,room.id,input.controller,now-LEASE).run();if(!result.meta.changes)throw new CloudError("Ya hay un controlador activo. Desconéctalo o espera unos segundos.",409);return {id:room.id,expires:room.expires,code:room.code,controller:lease};
 }
 async authorizeController(owner:string,roomId:string,credential:string){const room=await this.room(owner,roomId);if(credential===room.code)return room;if(!token.safeParse(credential).success||await hashToken(credential)!==room.join_hash)throw new CloudError("El enlace de conexión no es válido.",403);return room;}
 async view(room:Room,host:boolean):Promise<SessionView>{const now=this.clock(),commands=host?(await this.db.prepare("SELECT id,seq,command,created FROM remote_commands WHERE room=? AND seq>? AND created>? ORDER BY seq LIMIT 64").bind(room.id,room.acked,now-10000).all<{id:string;seq:number;command:string;created:number}>()).results.map(c=>{const saved=JSON.parse(c.command);return {id:c.id,seq:c.seq,created:c.created,...(saved.command?saved:{command:saved})};}):[];return {expires:room.expires,hostSeen:room.host_seen,controllerSeen:room.controller_seen,controllerId:room.controller_id,now,state:parse(room.state_json),offer:parse(room.offer_json),answer:parse(room.answer_json),frame:host&&now-room.face_updated<1000?parse(room.face_json):null,frameUpdated:room.face_updated,commands};}
 async host(room:Room,input:Extract<Operation,{op:"host"}>){await this.db.prepare("UPDATE remote_rooms SET host_seen=?,state_json=?,acked=MAX(acked,?),offer_json=COALESCE(?,offer_json),answer_json=CASE WHEN ? IS NOT NULL THEN NULL ELSE answer_json END WHERE id=?").bind(this.clock(),JSON.stringify(input.state),input.ack,input.offer?JSON.stringify(input.offer):null,input.offer?.id??null,room.id).run();return this.view(await this.room(room.owner,room.id),true);}
 async update(room:Room,input:Extract<Operation,{op:"controller"}>){this.controller(room,input.controller);if(input.answer&&input.answer.id!==parse<{id:string}>(room.offer_json)?.id)throw new CloudError("La conexión directa cambió. Reintentando…",422);const f=input.frame;const result=await this.db.prepare("UPDATE remote_rooms SET controller_seen=?,answer_json=COALESCE(?,answer_json),face_json=CASE WHEN ?>face_seq THEN ? ELSE face_json END,face_updated=CASE WHEN ?>face_seq THEN ? ELSE face_updated END,face_seq=MAX(face_seq,?) WHERE id=? AND controller_id=?").bind(this.clock(),input.answer?JSON.stringify(input.answer):null,f?.seq??-1,f?JSON.stringify(f):null,f?.seq??-1,this.clock(),f?.seq??-1,room.id,input.controller).run();if(!result.meta.changes)throw new CloudError("El controlador cambió. Vuelve a conectar.",409);return this.view(await this.room(room.owner,room.id),false);}
 async command(room:Room,input:Extract<Operation,{op:"command"}>){this.controller(room,input.controller);if(input.epoch&&input.epoch!==input.controller)throw new CloudError("El controlador cambió. Vuelve a conectar.",409);if(this.clock()-room.host_seen>LEASE)throw new CloudError("El estudio no responde. El pad no se ha enviado.",409);const count=await this.db.prepare("SELECT COUNT(*) AS n FROM remote_commands WHERE room=? AND seq>? AND created>?").bind(room.id,room.acked,this.clock()-10000).first<{n:number}>();if((count?.n??0)>=48)throw new CloudError("Espera a que el estudio reciba los pads.",429);await this.db.prepare("INSERT INTO remote_commands (id,room,command,created) VALUES (?,?,?,?) ON CONFLICT(id) DO NOTHING").bind(input.id,room.id,JSON.stringify({command:input.command,order:input.order,epoch:input.epoch}),this.clock()).run();return {id:input.id};}
 async leave(room:Room,controllerId:string){this.controller(room,controllerId);await this.db.prepare("UPDATE remote_rooms SET controller_id=NULL,controller_key=NULL,controller_seen=0,face_json=NULL,face_seq=-1,answer_json=NULL WHERE id=? AND controller_id=?").bind(room.id,controllerId).run();}
 async revoke(room:Room){await this.db.batch([this.db.prepare("DELETE FROM remote_commands WHERE room=?").bind(room.id),this.db.prepare("DELETE FROM remote_rooms WHERE id=?").bind(room.id)]);}
}
