"use client";

import type { CSSProperties } from "react";
import { useCallback, useEffect, useRef, useState } from "react";
import { Aperture, Box, Camera, Cloud, Cpu, Download, Expand, Eye, FileJson, Focus, FolderOpen, Globe2, Hand, Image as ImageIcon, Layers3, Loader2, Maximize2, Mic, MicOff, Monitor, Move3D, Pause, Play, Plus, Radio, RotateCcw, Save, ScanFace, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Trash2, Upload, Video, X, Zap, CircleHelp, Cable, Check, ChevronRight } from "lucide-react";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import { Checkbox } from "@/components/ui/checkbox";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from "@/components/ui/alert-dialog";
import { Toaster, toast } from "sonner";
import { defaults, robotDefaults, robotPartFlag,characterLibrarySchema,type SavedCharacter, type Config, type Mapping, type Signals, type TrackingFrame, MODES, SOURCES, autoMappings, parseConfig, rebindConfig } from "@/lib/engine/state";
import { POSE_CONNECTIONS, visiblePoint, trackingCoverage } from "@/lib/engine/rig";
import { RIG_ROLES, REQUIRED_BODY_ROLES, jointLabel, type RigRole } from "@/lib/engine/rig-roles";
import type { VtuberEngine, AvatarInfo } from "@/lib/engine/renderer";
import { animationMotionMode, liveTracking, playClip } from "@/lib/engine/motion";
import { HAND_CONNECTIONS } from "@/lib/engine/hands";
import { CameraTracking, MediaProblem, mediaProblem, checkMediaAccess, checkTrackingEngine, type CameraStatus } from "@/lib/engine/tracking";
import { fetchAsset } from "@/lib/engine/loader";
import {robotLookFromModel} from "@/lib/engine/robot";
import {CHARACTERS,POWERS,ANIMATION_PRESETS,powerPreset,type HighcoonId,type PowerId} from "@/lib/engine/highcoon";
import RemoteLink from "./remote-link";
import CharacterLibrary from "./character-library";
import {captureCharacter,storeCharacter,activateCharacter,characterCursor} from "@/lib/engine/characters";
import {performanceSchema} from "@/lib/engine/performance-state";
import {PoseTimeline} from "./pose-workshop";
import CreationStudio from "./creation-studio";
import type {CreationTask} from "@/lib/engine/authoring";
import ActionPads from "./action-pads";
import PadComposer from "./pad-composer";
import {nextNonce,type Performance,type PadView,type ActionPad} from "@/lib/engine/performance-state";
import {PadRuntime,padReady,type PadStage} from "@/lib/engine/pads";
import {robotPerformancePack} from "@/lib/engine/robot-performance";
import {RemoteHost,RemoteError} from "@/lib/remote/client";
import {applyRemoteCommand} from "@/lib/remote/actions";
import type {Pairing,RemoteStatus} from "@/lib/remote/protocol";

type CloudScene={id:string;name:string;updated:string};
type CloudData={id:string;updated:string;projects:CloudScene[];config:unknown;avatar:string|null;environment:string|null;media:string|null;error?:string};
type Stats={fps:number;signals:Signals;audio:Signals;inference:number;face:boolean;animation?:string;overload?:number;handTest?:string;poseTime?:number;poseEnded?:boolean;performanceMode?:string};
const initialStats:Stats={fps:0,signals:{},audio:{},inference:0,face:false};
const worldOptions=[["studio","Signal studio"],["grid","Infinite grid"],["orbit","Orbital chamber"],["garden","Terp garden"],["custom","My 3D environment"],["image","Image background"],["video","Video background"],["solid","Solid color"],["chroma","Chroma green"],["transparent","Transparent"]] as const;
function Range({label,value,onChange,min=0,max=3,step=.05,suffix="x"}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number;step?:number;suffix?:string}) {
  return <div className="range-control"><div><label>{label}</label><output>{value.toFixed(step>=1?0:2)}{suffix}</output></div><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(v[0])}/></div>;
}
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:readonly (readonly [string,string])[]}) {
  return <Select value={value||"none"} onValueChange={onChange}><SelectTrigger className="engine-select" aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent className="engine-select-menu" position="popper">{options.map(([v,l])=><SelectItem key={v} value={v||"none"}>{l}</SelectItem>)}</SelectContent></Select>;
}
function Toggle({label,checked,onChange,note}:{label:string;checked:boolean;onChange:(v:boolean)=>void;note?:string}) {
  return <label className="toggle-control"><span>{label}{note&&<small>{note}</small>}</span><Switch aria-label={label} checked={checked} onCheckedChange={onChange}/></label>;
}
function Color({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}) { return <label className="color-control"><span>{label}</span><span className="color-value">{value.toUpperCase()}<input type="color" aria-label={label} value={value} onChange={e=>onChange(e.target.value)}/></span></label>; }
function download(blob:Blob,name:string) {const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function jsonRequest(url:string,init?:RequestInit) {const r=await fetch(url,init);const data=await r.json() as CloudData;if(!r.ok)throw new Error(data.error||"This action could not be completed.");return data;}
function message(e:unknown){return e instanceof Error?e.message:"This action could not be completed.";}
function InputIssue({issue,retry}:{issue:MediaProblem;retry?:()=>void}) {
  return <div className="input-issue" role="alert"><strong>{issue.title}</strong><p>{issue.message}</p>{issue.standalone&&<a href={window.location.href} target="_blank" rel="noopener noreferrer">Open full studio</a>}{retry&&<button onClick={retry}>Retry tracking</button>}{issue.detail&&<details><summary>Error details</summary><code>{issue.code}: {issue.detail}</code></details>}</div>;
}

export default function Studio() {
  const [config,setConfig]=useState<Config>(defaults),configRef=useRef(config);configRef.current=config;
  const canvas=useRef<HTMLCanvasElement>(null),video=useRef<HTMLVideoElement>(null),overlay=useRef<HTMLCanvasElement>(null),engine=useRef<VtuberEngine|null>(null),tracking=useRef<CameraTracking|null>(null);
  const [info,setInfo]=useState<AvatarInfo|null>(null),[ready,setReady]=useState(false),[error,setError]=useState(""),[stats,setStats]=useState(initialStats);
  const [cameraStatus,setCameraStatus]=useState<CameraStatus>("off"),[cameraProgress,setCameraProgress]=useState(""),[cameraIssue,setCameraIssue]=useState<MediaProblem|null>(null),[inputReady,setInputReady]=useState(false),[isEmbedded,setIsEmbedded]=useState(false);
  const [micOn,setMicOn]=useState(false),[micStarting,setMicStarting]=useState(false),[micIssue,setMicIssue]=useState<MediaProblem|null>(null),[devices,setDevices]=useState<MediaDeviceInfo[]>([]),[cameraDevice,setCameraDevice]=useState("auto"),[micDevice,setMicDevice]=useState("auto");
  const [checkingTracking,setCheckingTracking]=useState(false),[trackingCheck,setTrackingCheck]=useState(""),[trackingCheckIssue,setTrackingCheckIssue]=useState<MediaProblem|null>(null);
  const [tab,setTab]=useState("act"),[mobilePanel,setMobilePanel]=useState("stage"),[clean,setClean]=useState(false),[help,setHelp]=useState(false),[outputSettings,setOutputSettings]=useState(false),[urlSlot,setUrlSlot]=useState<"avatar"|"world"|"media"|null>(null),[assetUrl,setAssetUrl]=useState("");
  const [busy,setBusy]=useState(""),[dragging,setDragging]=useState(false),[layerSearch,setLayerSearch]=useState(""),[worldName,setWorldName]=useState("No environment loaded"),[mediaName,setMediaName]=useState("No background loaded");
  const [cloudOpen,setCloudOpen]=useState(false),[scenes,setScenes]=useState<CloudScene[]>([]),[cloudError,setCloudError]=useState(""),[sceneId,setSceneId]=useState<string|null>(null),[deleteScene,setDeleteScene]=useState<CloudScene|null>(null),[savedAt,setSavedAt]=useState("");
  const cloudAssets=useRef<{avatar:string|null;environment:string|null;media:string|null}>({avatar:null,environment:null,media:null}),mediaFile=useRef<File|null>(null);
  const avatarInput=useRef<HTMLInputElement>(null),worldInput=useRef<HTMLInputElement>(null),mediaInput=useRef<HTMLInputElement>(null),settingsInput=useRef<HTMLInputElement>(null);
  const recorder=useRef<MediaRecorder|null>(null),recordStream=useRef<MediaStream|null>(null),recordChunks=useRef<Blob[]>([]),recordStart=useRef(0);
  const [recording,setRecording]=useState(false),[recordTime,setRecordTime]=useState(0),[manualSource,setManualSource]=useState("mouthOpen"),[manualValue,setManualValue]=useState(0);
  const actions=useRef<{save:()=>void;record:()=>void}>({save:()=>{},record:()=>{}});
  const micAction=useRef(0);
  const [powerAnimations,setPowerAnimations]=useState(true);
  const remote=useRef<RemoteHost|null>(null),remoteGeneration=useRef(0),remoteStarting=useRef(false);
  const [pair,setPair]=useState<Pairing|null>(null),[remoteBusy,setRemoteBusy]=useState(false),[remoteStatus,setRemoteStatus]=useState<RemoteStatus>({connected:false,transport:"waiting",camera:false});
  const remoteContext=useRef({info,ready,stats,busy});remoteContext.current={info,ready,stats,busy};
  const [rigJoint,setRigJoint]=useState<RigRole>("hips"),[coverage,setCoverage]=useState({hands:0,torso:false,arms:false,legs:false});
  const lastCoverage=useRef(0);
  const [autoKey,setAutoKey]=useState(false),[editorEnabled,setEditorEnabled]=useState(false),[editBank,setEditBank]=useState<ActionPad["bank"]>("A"),[editSlot,setEditSlot]=useState(0),padRuntime=useRef(new PadRuntime());
  const [creationTask,setCreationTask]=useState<CreationTask>("home"),[timelineAdvanced,setTimelineAdvanced]=useState(false),[creationActivity,setCreationActivity]=useState("");
  const libraryWrites=useRef<Promise<unknown>>(Promise.resolve());
  const padAction=useRef<(id:string,phase:"press"|"release")=>void>(()=>{});
  const commitConfig=useCallback((next:Config)=>{configRef.current=next;engine.current?.setConfig(next);setConfig(next);},[]);
  const commitPerformance=useCallback((performance:Performance)=>commitConfig({...configRef.current,performance}),[commitConfig]);
  function padStage():PadStage{const e=engine.current!;return {model:e.poseBinding.model,animations:e.info.animations,camera:()=>({position:e.camera.position.toArray() as [number,number,number],target:e.controls.target.toArray() as [number,number,number]}),frame:p=>e.frameCamera(p),burst:id=>e.powers.burst(id),clearPower:()=>{e.powers.remaining=0;}};}
  function performPad(c:Config,id:string,phase:"press"|"release"){if(phase==="release")return padRuntime.current.release(c,id);const pad=c.performance.pads.find(p=>p.id===id);if(!pad)throw new Error("Este pad ya no está en el deck.");if(!engine.current||!remoteContext.current.ready||remoteContext.current.busy)throw new Error("El personaje todavía está cargando.");setEditorEnabled(false);return padRuntime.current.press(c,pad,padStage());}
  function triggerPad(id:string,phase:"press"|"release"){try{commitConfig(performPad(configRef.current,id,phase));}catch(e){toast.error(message(e));}}
  padAction.current=triggerPad;
  function padViews():PadView[]{const c=configRef.current,e=engine.current;return c.performance.pads.map(({action,...pad})=>({...pad,active:padRuntime.current.active.has(pad.id),ready:!!e&&padReady({...pad,action},c,{model:e.poseBinding.model,animations:e.info.animations})}));}
  function prepareModelChange(){const c=padRuntime.current.releaseAll(snapshotConfig());commitConfig({...c,characters:{...c.characters,selected:null}});setEditorEnabled(false);}
  const change=useCallback(<K extends keyof Config>(group:K,value:Partial<Config[K]>)=>setConfig(c=>({...c,[group]:{...(c[group] as object),...(value as object)}})),[]);
  const top=useCallback((key:keyof Config,value:Config[keyof Config])=>setConfig(c=>({...c,[key]:value})),[]);

  useEffect(()=>{
    let cancelled=false;
    if(video.current){tracking.current=new CameraTracking(video.current,frame=>{engine.current?.setTracking(frame);drawTracking(frame);if(performance.now()-lastCoverage.current>300){setCoverage(trackingCoverage(frame,configRef.current.tracking.confidence));setStats(s=>({...s,face:!!frame.face?.length,inference:frame.inference}));lastCoverage.current=performance.now();}},(status,detail)=>{setCameraStatus(status);setCameraProgress(detail||"");if(status!=="on")setCoverage({hands:0,torso:false,arms:false,legs:false});if(status==="off"){setStats(s=>({...s,face:false}));engine.current?.setTracking({signals:{},face:[],hands:[],pose:[],poseWorld:[],inference:0,time:performance.now()});}},issue=>setCameraIssue(issue));setInputReady(true);}
    setIsEmbedded(window.self!==window.top);void enumerate();
    navigator.mediaDevices?.addEventListener("devicechange",enumerate);
    void import("@/lib/engine/renderer").then(async ({VtuberEngine})=>{
      if(cancelled||!canvas.current)return;
      try {
        const e=new VtuberEngine(canvas.current);engine.current=e;e.stats=setStats;setInfo(e.info);
        setConfig(c=>({...c,performance:c.performance.clips.length||c.performance.poses.length?c.performance:robotPerformancePack(e.poseBinding,c.performance),mappings:autoMappings(e.info.morphs)}));if(!cancelled)setReady(true);
      }catch(e){setError("The 3D studio could not start. Enable hardware acceleration in your browser and reload. "+message(e));}
    }).catch(e=>{if(!cancelled)setError("The studio could not load. Reload and try again. "+message(e));});
    return ()=>{cancelled=true;++remoteGeneration.current;remote.current?.dispose();navigator.mediaDevices?.removeEventListener("devicechange",enumerate);tracking.current?.stop();if(recorder.current?.state==="recording"){recorder.current.onstop=null;recorder.current.stop();}recordStream.current?.getTracks().forEach(t=>t.stop());engine.current?.dispose();};
  },[]);
  useEffect(()=>{engine.current?.setConfig(config);},[config,ready]);
  useEffect(()=>{engine.current?.editor.setEnabled(editorEnabled&&tab==="pose"&&!clean);},[editorEnabled,tab,clean,ready,info]);
  useEffect(()=>{const timer=setInterval(()=>{const c=configRef.current,next=padRuntime.current.expire(c);if(next!==c)commitConfig(next);},100);return()=>clearInterval(timer);},[commitConfig]);
  useEffect(()=>{const c=configRef.current;if(stats.poseEnded&&c.performance.playing&&!c.performance.loop)commitPerformance({...c.performance,playing:false,time:stats.poseTime||0});},[stats.poseEnded,stats.poseTime,commitPerformance]);
  useEffect(()=>{if(!remoteStatus.connected&&remote.current){const c=configRef.current,next=padRuntime.current.releaseHolds(c);if(next!==c)commitConfig(next);}},[remoteStatus.connected,commitConfig]);
  useEffect(()=>{if(tracking.current?.stream)tracking.current.configure(config.tracking);},[config.tracking.hands,config.tracking.pose,config.tracking.rate,config.tracking.bodyMode]);
  useEffect(()=>{if(!recording)return;const timer=setInterval(()=>setRecordTime(Math.floor((performance.now()-recordStart.current)/1000)),500);return()=>clearInterval(timer);},[recording]);
  useEffect(()=>{
    const held=new Map<string,string>();
    const key=(e:KeyboardEvent)=>{
      if(e.key==="Escape")setClean(false);
      const target=e.target as HTMLElement;if(["INPUT","TEXTAREA","BUTTON","SELECT"].includes(target.tagName)||target.isContentEditable||document.querySelector('[role="dialog"]'))return;
      if(e.code==="Space"){e.preventDefault();setConfig(c=>({...c,frozen:!c.frozen}));}
      if(!e.repeat&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&/^[0-9]$/.test(e.key)){const c=configRef.current;if(c.performance.bank==="moods"){if(/^[1-6]$/.test(e.key))setConfig(c=>({...c,mode:MODES[Number(e.key)-1]}));}else{const slot=e.key==="0"?9:Number(e.key)-1,p=c.performance.pads.find(p=>p.bank===c.performance.bank&&p.slot===slot);if(p){e.preventDefault();if(p.trigger==="hold")held.set(e.code,p.id);padAction.current(p.id,"press");}}}
      if((e.ctrlKey||e.metaKey)&&e.key==="s"){e.preventDefault();actions.current.save();}
    },up=(e:KeyboardEvent)=>{const id=held.get(e.code);if(id){held.delete(e.code);padAction.current(id,"release");}},blur=()=>{for(const id of held.values())padAction.current(id,"release");held.clear();};window.addEventListener("keydown",key);window.addEventListener("keyup",up);window.addEventListener("blur",blur);return()=>{blur();window.removeEventListener("keydown",key);window.removeEventListener("keyup",up);window.removeEventListener("blur",blur);};
  },[]);
  useEffect(()=>{
    const context=(document as Document&{modelContext?:{registerTool:(t:unknown,o:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
    const tools=[
      {name:"sgx_read_studio",description:"Read the current performance mode, character and environment settings.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode:configRef.current.mode,world:configRef.current.world,tracking:configRef.current.tracking})},
      {name:"sgx_set_performance_mode",description:"Apply one of the six visible performance pads to the character.",inputSchema:{type:"object",properties:{mode:{type:"string",enum:MODES}},required:["mode"],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const mode=(input as {mode:string})?.mode;if(!MODES.includes(mode as Config["mode"]))throw new Error("Unknown performance mode.");setConfig(c=>({...c,mode:mode as Config["mode"]}));return{mode};}},
      {name:"sgx_set_environment",description:"Change the visible environment preset. Custom assets must be loaded through the studio.",inputSchema:{type:"object",properties:{type:{type:"string",enum:["studio","grid","orbit","garden","solid","chroma","transparent"]}},required:["type"],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const type=(input as {type:string})?.type;if(!["studio","grid","orbit","garden","solid","chroma","transparent"].includes(type))throw new Error("Unknown environment.");setConfig(c=>({...c,world:{...c.world,type:type as Config["world"]["type"]}}));return{type};}}
    ];
    for(const tool of tools)try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
    return()=>lifecycle.abort();
  },[]);

  function drawTracking(frame:TrackingFrame) {
    const ctx=overlay.current?.getContext("2d");if(!ctx||!overlay.current)return;const aspect=video.current?.videoWidth&&video.current?.videoHeight?video.current.videoWidth/video.current.videoHeight:4/3; const w=640,h=Math.round(w/aspect); if(overlay.current.width!==w)overlay.current.width=w;if(overlay.current.height!==h)overlay.current.height=h;const preview=video.current?.parentElement;if(preview)preview.style.aspectRatio=String(aspect);ctx.clearRect(0,0,w,h);ctx.fillStyle="#00eeee";ctx.strokeStyle="#fdcc0d";ctx.lineWidth=1.2;
    if(!configRef.current.tracking.overlay)return;
    for(const i of [1,4,33,133,159,145,263,362,386,374,61,291,13,14,70,300,10,152]){const p=frame.face?.[i];if(p){ctx.beginPath();ctx.arc(p.x*w,p.y*h,2,0,Math.PI*2);ctx.fill();}}
    for(const hand of frame.hands||[])for(const[a,b]of HAND_CONNECTIONS){const p=hand.points[a],q=hand.points[b];if(!visiblePoint(p,0)||!visiblePoint(q,0))continue;ctx.beginPath();ctx.moveTo(p.x*w,p.y*h);ctx.lineTo(q.x*w,q.y*h);ctx.stroke();}
    ctx.strokeStyle="#00eeee";ctx.lineWidth=2;
    for(const[a,b]of POSE_CONNECTIONS){if(configRef.current.tracking.bodyMode!=="full"&&(a>=25||b>=25))continue;const p=frame.pose?.[a],q=frame.pose?.[b];if(!visiblePoint(p,configRef.current.tracking.confidence,true)||!visiblePoint(q,configRef.current.tracking.confidence,true))continue;ctx.beginPath();ctx.moveTo(p.x*w,p.y*h);ctx.lineTo(q.x*w,q.y*h);ctx.stroke();for(const point of [p,q]){ctx.beginPath();ctx.arc(point.x*w,point.y*h,3,0,Math.PI*2);ctx.fill();}}
  }
  function takeLiveTracking(input:Parameters<typeof liveTracking>[1]={}){
    engine.current?.cancelHandRigTest();engine.current?.editor.setEnabled(false);setEditorEnabled(false);
    const c=padRuntime.current.releaseAll(configRef.current),next=liveTracking(c,input);commitConfig(next);return next;
  }
  async function trackHandsAndArms(){
    takeLiveTracking({hands:true,body:configRef.current.tracking.bodyMode});
    if(!pair&&cameraStatus==="off")await startCamera();
  }
  function testHands(){if(stats.handTest){engine.current?.cancelHandRigTest();return;}takeLiveTracking({hands:true});engine.current?.testHandRig();}
  function bodyTracking(value:string){if(value!=="off")takeLiveTracking({body:value==="full"?"full":"upper",...(value==="full"?{hands:true}:{})});else change("tracking",{pose:false});if(value==="full")presetCamera("full");}
  function assignJoint(value:string){const rigMap={...config.avatar.rigMap};if(value==="auto")delete rigMap[rigJoint];else rigMap[rigJoint]=value;change("avatar",{rigMap});}
  async function enumerate(){try{if(navigator.mediaDevices?.enumerateDevices)setDevices(await navigator.mediaDevices.enumerateDevices());}catch{}}
  async function startCamera(device=cameraDevice) {
    if(remote.current||remoteStarting.current){toast.info("Cierra la conexión remota antes de usar la cámara local.");return;}
    if(!tracking.current)return;setCameraIssue(null);const live=takeLiveTracking();
    try{await tracking.current.start(live.tracking,device==="auto"?undefined:device);await enumerate();}
    catch(e){setCameraIssue(mediaProblem(e));}
  }
  async function toggleCamera() {
    if(cameraStatus!=="off"){tracking.current?.stop();setCameraStatus("off");overlay.current?.getContext("2d")?.clearRect(0,0,640,480);return;}
    await startCamera();
  }
  async function toggleMic(){if(!engine.current)return;const action=++micAction.current;setMicIssue(null);try{if(micOn||micStarting){setMicOn(false);setMicStarting(false);await engine.current.stopMic();}else{checkMediaAccess("microphone");setMicStarting(true);await engine.current.startMic(micDevice==="auto"?undefined:micDevice);if(action!==micAction.current)return;setMicOn(!!engine.current.mic);await enumerate();}}catch(e){if(action!==micAction.current)return;setMicOn(false);setMicIssue(mediaProblem(e,"microphone"));}finally{if(action===micAction.current)setMicStarting(false);}}
  async function runTrackingCheck(){if(checkingTracking)return;setCheckingTracking(true);setTrackingCheckIssue(null);setTrackingCheck("Loading tracking engine…");try{const warnings=await checkTrackingEngine(configRef.current.tracking,setTrackingCheck);setTrackingCheck(warnings.length?"Face tracking ready. "+warnings.join(" "):"Tracking engine ready. Start the camera to test your performance.");}catch(error){const issue=mediaProblem(error,"tracking");setTrackingCheck("Tracking engine check failed.");setTrackingCheckIssue(new MediaProblem(issue.code,issue.title,"Enable hardware acceleration in your browser, reload the studio, and run this check again.","tracking",issue.detail));}finally{setCheckingTracking(false);}}
  async function importAvatar(files:File[]) {if(!files.length||!engine.current)return;prepareModelChange();setBusy("Loading character");try{const loaded=await engine.current.loadAvatar(files);if(loaded){setInfo(loaded);cloudAssets.current.avatar=null;setConfig(c=>({...c,performance:{...c.performance,mode:"live",playing:false},robot:robotLookFromModel(engine.current!.avatarRoot)||c.robot,avatar:{...c.avatar,hidden:[],headBone:"auto",animation:"none",rigMap:{},character:"custom",motionMode:"tracking"},mappings:autoMappings(loaded.morphs)}));toast.success("Character loaded · "+loaded.morphs.length+" morph targets");}}catch(e){toast.error(message(e));}finally{setBusy("");}}
  async function importWorld(files:File[]){if(!files.length||!engine.current)return;setBusy("Loading environment");try{const name=await engine.current.loadWorld(files);if(name){setWorldName(name);cloudAssets.current.environment=null;change("world",{type:"custom"});toast.success("3D environment loaded");}}catch(e){toast.error(message(e));}finally{setBusy("");}}
  async function importMedia(file:File){if(!engine.current)return;setBusy("Loading background");try{await engine.current.loadMedia(file);mediaFile.current=file;cloudAssets.current.media=null;setMediaName(file.name);change("world",{type:file.type.startsWith("video/")?"video":"image"});}catch(e){toast.error(message(e));}finally{setBusy("");}}
  async function loadUrl(){if(!assetUrl||!urlSlot)return;setBusy("Fetching asset");try{const file=await fetchAsset(assetUrl);if(urlSlot==="avatar")await importAvatar([file]);if(urlSlot==="world")await importWorld([file]);if(urlSlot==="media")await importMedia(file);setUrlSlot(null);setAssetUrl("");}catch(e){toast.error(message(e));}finally{setBusy("");}}
  function chooseRobot(){if(!engine.current||busy)return;prepareModelChange();const loaded=engine.current.useBuiltin();setInfo(loaded);cloudAssets.current.avatar=null;setConfig(c=>({...c,frozen:false,performance:{...c.performance,mode:"live",playing:false},avatar:defaults().avatar,mappings:autoMappings(loaded.morphs)}));toast.success("SGX Robot · energy face + complete rig");}
  function resetAvatar(){chooseRobot();setConfig(c=>({...c,robot:robotDefaults()}));}
  async function downloadRobot(){try{const blob=await engine.current?.modelBlob();if(blob)download(blob,"SGX-Robot.glb");}catch(e){toast.error(message(e));}}
  async function chooseCharacter(id:HighcoonId){if(!engine.current||busy)return;prepareModelChange();setBusy("Loading Highcoon");try{const loaded=await engine.current.loadCharacter(id);if(loaded){setInfo(loaded);cloudAssets.current.avatar=null;setConfig(c=>({...c,performance:{...c.performance,mode:"live",playing:false},avatar:{...defaults().avatar,character:id,animation:"Idle",motionMode:animationMotionMode(c)},mappings:autoMappings(loaded.morphs)}));toast.success(loaded.name+" · facial rig + 31 animations");}}catch(e){toast.error(message(e));}finally{setBusy("");}}
  function playAnimation(name:string,loop=true){setEditorEnabled(false);setConfig(c=>({...playClip(c,name,loop),performance:{...c.performance,mode:"live",playing:false}}));}
  function selectPower(id:PowerId){if(engine.current)engine.current.powers.remaining=0;const play=powerAnimations&&!!info?.animations.length&&id!=="none";if(play)setEditorEnabled(false);setConfig(c=>{const next=powerPreset(c,id,play);return play?{...next,performance:{...next.performance,mode:"live",playing:false}}:next;});}
  async function connectRemote(){
    if(remoteStarting.current||remote.current&&!remoteStatus.expired)return;
    remote.current?.dispose();remote.current=null;remoteStarting.current=true;setRemoteBusy(true);tracking.current?.stop();setCameraIssue(null);takeLiveTracking();
    const generation=++remoteGeneration.current;setRemoteStatus({connected:false,transport:"waiting",camera:false});
    try{const host=await RemoteHost.create({
      frame:frame=>{engine.current?.setTracking(frame);if(performance.now()-lastCoverage.current>300){setCoverage(trackingCoverage(frame,configRef.current.tracking.confidence));lastCoverage.current=performance.now();}},
      preview:()=>engine.current?.previewImage()||null,
      snapshot:()=>{const {info,ready,stats,busy}=remoteContext.current,c=configRef.current;return {model:c.characters.items.find(p=>p.id===c.characters.selected)?.name||info?.name||"SGX Robot",animations:info?.animations||[],mode:c.mode,power:c.power.id,animation:c.avatar.animation,frozen:c.frozen,face:stats.face,ready:ready&&!busy,hands:c.puppet,pads:padViews(),tracking:{hands:c.tracking.hands,body:c.tracking.pose?c.tracking.bodyMode:"off"},performance:(()=>{const clip=c.performance.clips.find(p=>p.id===c.performance.clip);return clip?{name:clip.name,time:Math.min(clip.duration,engine.current?.posePlayer.time||0),duration:clip.duration,playing:c.performance.playing}:undefined;})()};},
      command:command=>{const e=engine.current,context=remoteContext.current;if(!e||!context.ready||context.busy)throw new Error("El personaje todavía está cargando.");const c=command.type==="tracking"?padRuntime.current.releaseAll(configRef.current):configRef.current,next=applyRemoteCommand(c,command,{animations:context.info?.animations||[],face:(e.raw.faceDetected??!!e.raw.face?.length)&&performance.now()-e.raw.time<650,calibrate:()=>e.calibrate(),frame:p=>e.frameCamera(p),burst:()=>e.powers.burst(c.power.id),clearPower:()=>{e.powers.remaining=0;},pad:performPad});if(command.type==="tracking"||command.type==="animation"||command.type==="reset"||command.type==="power"&&next.performance.mode==="live")setEditorEnabled(false);if(command.type==="reset")padRuntime.current.clear();if(command.type==="tracking"){e.cancelHandRigTest();e.editor.setEnabled(false);}commitConfig(next);},status:setRemoteStatus,
    });if(generation!==remoteGeneration.current){void host.revoke().catch(()=>{});return;}remote.current=host;setPair(host.pairing);toast.success("Escanea el QR desde tu teléfono");}catch(e){if(generation===remoteGeneration.current){setPair(null);setRemoteStatus({connected:false,transport:"waiting",camera:false,error:message(e)});}}finally{if(generation===remoteGeneration.current){remoteStarting.current=false;setRemoteBusy(false);}}
  }
  async function disconnectRemote(){const host=remote.current;if(!host)return;commitConfig(padRuntime.current.releaseHolds(configRef.current));setRemoteBusy(true);try{try{await host.revoke();}catch(e){if(!(e instanceof RemoteError&&e.status===410))throw e;}remote.current=null;setPair(null);setRemoteStatus({connected:false,transport:"waiting",camera:false});engine.current?.setTracking({signals:{},face:[],faceDetected:false,hands:[],pose:[],inference:0,time:performance.now()});}catch(e){setRemoteStatus(s=>({...s,connected:false,expired:true,error:message(e)}));}finally{setRemoteBusy(false);}}
  function layerVisible(id:string,name:string){const flag=info?.robot?robotPartFlag(name):undefined;return !config.avatar.hidden.includes(id)&&(!flag||config.robot[flag]);}
  function toggleLayer(id:string,name:string,visible:boolean){const flag=info?.robot?robotPartFlag(name):undefined;setConfig(c=>({...c,avatar:{...c.avatar,hidden:visible?c.avatar.hidden.filter(n=>n!==id):[...c.avatar.hidden,id]},robot:flag&&visible?{...c.robot,[flag]:true}:c.robot}));}
  function showAllLayers(){setConfig(c=>({...c,avatar:{...c.avatar,hidden:[]},robot:info?.robot?{...c.robot,helmet:true,antenna:true,halo:true,sigil:true}:c.robot}));}
  function updateMapping(id:string,patch:Partial<Mapping>){setConfig(c=>({...c,mappings:c.mappings.map(m=>m.id===id?{...m,...patch}:m)}));}
  function addMapping(){const target=info?.morphs[0]||info?.nodes[0]?.id;if(!target)return;setConfig(c=>({...c,mappings:[...c.mappings,{id:crypto.randomUUID(),source:"smile",kind:info?.morphs.length?"morph":"scale",target,gain:1,offset:0,enabled:true}]}));}
  function presetCamera(preset:"bust"|"portrait"|"full"){engine.current?.frameCamera(preset);}
  function snapshotConfig(performanceValue=configRef.current.performance){const c={...configRef.current,performance:performanceValue},e=engine.current,time=c.performance.playing?(e?.posePlayer.time??c.performance.time):c.performance.time,performance={...c.performance,playing:false,time},next={...c,performance,camera:e?{position:e.camera.position.toArray() as [number,number,number],target:e.controls.target.toArray() as [number,number,number]}:c.camera};return {...next,characters:{...c.characters,items:c.characters.items.map(p=>p.id===c.characters.selected?{...p,robot:c.robot,avatar:c.avatar,face:c.face,power:c.power,mappings:c.mappings,cursor:characterCursor(next,time)}:p)}};}
  function writeCharacterLibrary(c:Config){const body=JSON.stringify({characters:c.characters,performance:c.performance}),job=libraryWrites.current.catch(()=>{}).then(()=>jsonRequest("/api/characters",{method:"POST",headers:{"content-type":"application/json"},body}));libraryWrites.current=job;return job;}
  async function persistPerformance(p:Performance){
    const e=engine.current;if(!e)throw new Error("Espera a que termine de cargar el personaje.");
    if(busy)throw new Error("Hay otro guardado en curso. Reintenta en unos segundos.");
    const binding=e.poseBinding;setBusy("Guardando personaje y acciones");
    try{let c=snapshotConfig(p);
      if(!c.characters.items.some(item=>item.id===c.characters.selected)){
        if(c.characters.items.length>=24)throw new Error("La biblioteca está llena. Selecciona un personaje guardado antes de guardar esta acción.");
        let asset=c.avatar.character==="custom"?cloudAssets.current.avatar:null;
        if(c.avatar.character==="custom"&&!asset&&e.avatar){asset=await uploadCloud(e.avatar.blob,e.info.name);cloudAssets.current.avatar=asset;}
        c=storeCharacter(c,captureCharacter({...c,performance:{...c.performance,model:binding.model}},(info?.name||"Mi personaje").slice(0,60),asset,c.performance.time));
      }
      await writeCharacterLibrary(c);
      if(engine.current?.poseBinding===binding){const current=configRef.current,owner=c.characters.selected;commitConfig({...current,characters:c.characters,performance:{...current.performance,poses:current.performance.poses.map(item=>!item.character&&item.model===binding.model&&owner?{...item,character:owner}:item),clips:current.performance.clips.map(item=>!item.character&&item.model===binding.model&&owner?{...item,character:owner}:item)}});}
    }finally{setBusy("");}
  }
  async function saveCharacterLibrary(c=snapshotConfig()){await writeCharacterLibrary(c);toast.success("Personajes, poses, animaciones y pads guardados en tu cuenta.");}
  async function saveCharacter(name:string,asNew:boolean){const e=engine.current;if(!e||busy)return;setBusy("Saving character");try{const c=snapshotConfig();let asset=c.avatar.character==="custom"?cloudAssets.current.avatar:null;if(c.avatar.character==="custom"&&!asset&&e.avatar){asset=await uploadCloud(e.avatar.blob,e.info.name);cloudAssets.current.avatar=asset;}
    const id=!asNew&&c.characters.selected?c.characters.selected:crypto.randomUUID();let p=captureCharacter({...c,performance:{...c.performance,model:e.poseBinding.model}},name,asset,c.performance.time,id),next=c;
    if(asNew&&c.characters.selected&&p.cursor.mode==="clip"){const clip=c.performance.clips.find(x=>x.id===p.cursor.clip&&x.model===e.poseBinding.model);if(clip&&c.performance.clips.length<24){const copy={...clip,id:crypto.randomUUID(),character:id,keyframes:clip.keyframes.map(k=>({...k,id:crypto.randomUUID()}))};next={...c,performance:{...c.performance,clips:[...c.performance.clips,copy],clip:copy.id}};p={...p,cursor:{...p.cursor,clip:copy.id}};}}
    next=storeCharacter(next,p);await writeCharacterLibrary(next);commitConfig(next);toast.success(name+" saved · character, timeline and action deck");
  }catch(err){toast.error(message(err));}finally{setBusy("");}}
  async function loadSavedCharacter(p:SavedCharacter,incoming?:Config){const e=engine.current;if(!e||busy)return;const c=incoming||snapshotConfig();prepareModelChange();setBusy("Loading saved character");try{let loaded:AvatarInfo|null|undefined=null;if(p.avatar.character==="custom"){if(!p.asset)throw new Error("This character needs its saved model file.");loaded=await e.loadAvatar([await cloudFile(p.asset)]);}else if(p.avatar.character==="sgx")loaded=e.useBuiltin();else loaded=await e.loadCharacter(p.avatar.character);if(!loaded)throw new Error("The character could not load.");setInfo(loaded);cloudAssets.current.avatar=p.asset;const next=activateCharacter(c,p,e.poseBinding.model);commitConfig(rebindConfig(next,loaded.nodes.map(n=>n.id),loaded.morphs));toast.success(p.name+" · last pose / timeline restored");}catch(err){commitConfig(c);toast.error(message(err));}finally{setBusy("");}}
  async function deleteCharacter(id:string){const c=snapshotConfig(),next={...c,characters:{selected:c.characters.selected===id?null:c.characters.selected,items:c.characters.items.filter(p=>p.id!==id)}};try{await writeCharacterLibrary(next);commitConfig(next);toast.success("Character removed. Animation clips stay in your performance library.");}catch(e){toast.error(message(e));}}
  const restoredLibrary=useRef(false);
  useEffect(()=>{if(!ready||restoredLibrary.current)return;restoredLibrary.current=true;let cancelled=false;void (async()=>{try{const data=await jsonRequest("/api/characters");if(!data.config||cancelled)return;const saved=data.config as {characters:unknown;performance:unknown},characters=characterLibrarySchema.parse(saved.characters),performance=performanceSchema.parse(saved.performance),next={...configRef.current,characters,performance:{...performance,playing:false}},p=characters.items.find(p=>p.id===characters.selected);if(p)await loadSavedCharacter(p,next);else commitConfig(next);}catch(e){if(!cancelled)toast.error("Could not restore the saved library. "+message(e));}})();return()=>{cancelled=true;};},[ready]);
  function exportSettings(){download(new Blob([JSON.stringify(snapshotConfig())],{type:"application/json"}),"SGX-performance.sgx.json");toast.success("Settings, poses, keyframes and pads exported. Model files are stored with cloud scenes.");}
  async function importSettings(file:File){try{if(file.size>1500000)throw new Error("Settings file is too large.");const raw=JSON.parse(await file.text()),next=parseConfig(raw);prepareModelChange();if(engine.current&&raw.avatar?.character&&next.avatar.character!=="custom"){if(next.avatar.character==="sgx")setInfo(engine.current.useBuiltin());else{const loaded=await engine.current.loadCharacter(next.avatar.character);if(loaded)setInfo(loaded);}cloudAssets.current.avatar=null;}const model=engine.current?.info||info,bound=model?rebindConfig(next,model.nodes.map(n=>n.id),model.morphs):next;setConfig({...bound,performance:{...bound.performance,playing:false},avatar:{...bound.avatar,...(!raw.avatar?.character?{character:configRef.current.avatar.character}:{})},demo:false,frozen:false});toast.success("Performance settings imported");}catch(e){toast.error("Use a valid SGX settings file. "+message(e));}}
  async function snapshot(){try{const surface=engine.current?.cleanFrameCanvas();if(!surface)return;const blob=await new Promise<Blob|null>(resolve=>surface.toBlob(resolve,"image/png"));if(blob)download(blob,"SGX-frame.png");}catch(e){toast.error(message(e));}}
  function toggleRecord() {
    if(recorder.current?.state==="recording"){recorder.current.stop();return;}
    if(!canvas.current||!ready)return;
    if(typeof MediaRecorder==="undefined"||!canvas.current.captureStream){toast.error("Recording is unavailable in this browser. Capture the clean output in OBS.");return;}
    try{
      const type=["video/webm;codecs=vp9,opus","video/webm;codecs=vp8,opus","video/webm","video/mp4"].find(t=>MediaRecorder.isTypeSupported(t));if(!type)throw new Error("No recording format is supported in this browser.");
      const e=engine.current!;e.captureActive=true;const stream=e.cleanFrameCanvas().captureStream(Number(config.output.fps));for(const track of e.mic?.getAudioTracks()||[])stream.addTrack(track.clone());recordStream.current=stream;recordChunks.current=[];let bytes=0;
      const rec=new MediaRecorder(stream,{mimeType:type,videoBitsPerSecond:config.output.resolution==="1440"?16000000:config.output.resolution==="1080"?10000000:6000000});recorder.current=rec;
      rec.ondataavailable=e=>{if(e.data.size){recordChunks.current.push(e.data);bytes+=e.data.size;if(bytes>350*1024*1024&&rec.state==="recording"){rec.stop();toast("Recording saved at the memory limit. Start a new take.");}}};
      rec.onstop=()=>{if(engine.current)engine.current.captureActive=false;const blob=new Blob(recordChunks.current,{type});if(blob.size)download(blob,"SGX-take-"+new Date().toISOString().replace(/[:.]/g,"-")+(type.includes("mp4")?".mp4":".webm"));recordChunks.current=[];recordStream.current?.getTracks().forEach(t=>t.stop());recordStream.current=null;recorder.current=null;setRecording(false);toast.success("Take downloaded");};
      rec.onerror=()=>{toast.error("Recording stopped unexpectedly. Try capturing the output in OBS.");if(rec.state!=="inactive")rec.stop();};
      rec.start(1000);recordStart.current=performance.now();setRecordTime(0);setRecording(true);
      toast("Recording the clean canvas"+(micOn?" + microphone":"")+".");
    }catch(e){if(engine.current)engine.current.captureActive=false;recordStream.current?.getTracks().forEach(t=>t.stop());toast.error(message(e));}
  }
  async function uploadCloud(blob:Blob,name:string){const data=await jsonRequest("/api/assets",{method:"POST",headers:{"content-type":blob.type||"application/octet-stream","x-file-name":encodeURIComponent(name)},body:blob});return data.id as string;}
  async function saveCloud() {
    if(!engine.current||busy)return;setBusy("Saving cloud scene");
    try{
      const c={...snapshotConfig(),demo:false,frozen:false};const keys={...cloudAssets.current};
      if(!info?.builtin&&!keys.avatar){keys.avatar=await uploadCloud(engine.current.avatar!.blob,info?.name||"character.glb");cloudAssets.current.avatar=keys.avatar;}
      if(engine.current.importedWorld&&!keys.environment){keys.environment=await uploadCloud(engine.current.importedWorld.blob,engine.current.importedWorld.name);cloudAssets.current.environment=keys.environment;}
      if(mediaFile.current&&!keys.media){keys.media=await uploadCloud(mediaFile.current,mediaFile.current.name);cloudAssets.current.media=keys.media;}
      const data=await jsonRequest("/api/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:sceneId||undefined,config:c,...keys})});setSceneId(data.id);setSavedAt(data.updated);if(c.characters.items.length)await saveCharacterLibrary(c);toast.success("Cloud scene saved · models, layers & mappings");
    }catch(e){toast.error(message(e));}finally{setBusy("");}
  }
  actions.current={save:()=>{void saveCloud();},record:toggleRecord};
  async function listScenes(){setCloudOpen(true);setCloudError("");try{const data=await jsonRequest("/api/projects");setScenes(data.projects);}catch(e){setCloudError(message(e));}}
  async function cloudFile(id:string){const r=await fetch("/api/assets/"+id);if(!r.ok){const d=await r.json() as {error?:string};throw new Error(d.error||"Asset could not load.");}return new File([await r.blob()],decodeURIComponent(r.headers.get("x-file-name")||"asset.glb"),{type:r.headers.get("content-type")||"model/gltf-binary"});}
  async function openScene(id:string){if(!engine.current)return;prepareModelChange();setBusy("Opening cloud scene");try{
    const data=await jsonRequest("/api/projects/"+id),next=parseConfig(data.config);
    const results=await Promise.all([data.avatar?cloudFile(data.avatar):null,data.environment?cloudFile(data.environment):null,data.media?cloudFile(data.media):null]);
    if(results[0]){const loaded=await engine.current.loadAvatar([results[0]]);if(loaded)setInfo(loaded);}else if(next.avatar.character==="highcoon-classic"||next.avatar.character==="highcoon-full-spectrum"){const loaded=await engine.current.loadCharacter(next.avatar.character);if(loaded)setInfo(loaded);}else setInfo(engine.current.useBuiltin());
    if(results[1]){const name=await engine.current.loadWorld([results[1]]);setWorldName(name||"Environment");}else{engine.current.clearWorld();setWorldName("No environment loaded");}
    if(results[2]){await engine.current.loadMedia(results[2]);mediaFile.current=results[2];setMediaName(results[2].name);}else{engine.current.clearMedia();mediaFile.current=null;setMediaName("No background loaded");}
    const bound=rebindConfig(next,engine.current.info.nodes.map(n=>n.id),engine.current.info.morphs);cloudAssets.current={avatar:data.avatar,environment:data.environment,media:data.media};setConfig({...bound,performance:{...bound.performance,playing:false},demo:false,frozen:false});setSceneId(id);setSavedAt(data.updated);setCloudOpen(false);toast.success("Scene opened · poses, keyframes and pads restored");
  }catch(e){toast.error(message(e));}finally{setBusy("");}}
  async function removeScene(){if(!deleteScene)return;try{await jsonRequest("/api/projects/"+deleteScene.id,{method:"DELETE"});setScenes(s=>s.filter(p=>p.id!==deleteScene.id));if(sceneId===deleteScene.id){setSceneId(null);setSavedAt("");}toast.success("Scene deleted");}catch(e){toast.error(message(e));}finally{setDeleteScene(null);}}
  const flatOutput=["transparent","chroma"].includes(config.world.type);
  const modesIcons=[Focus,Zap,Eye,ScanFace,Sparkles,Cpu];
  const resolvedRig={...info?.rig,...config.avatar.rigMap},missingRig=REQUIRED_BODY_ROLES.filter(role=>!info?.nodes.some(n=>n.id===resolvedRig[role]));

  return <main className={"studio "+(clean?"is-clean":"")}>
    <Toaster theme="dark" position="bottom-center" richColors/>
    <header className="studio-header">
      <div className="brand"><div className="brand-mark">SGX<span/></div><div><h1>vTuber Engine</h1><p>SPATIALGINEERS</p></div><span className="version-tag">HC</span></div>
      <div className="project-name"><span className={savedAt?"saved-indicator":"draft-indicator"}/><input aria-label="Performance name" value={config.name} maxLength={100} onChange={e=>top("name",e.target.value||"Untitled performance")}/><small>{savedAt?"Cloud scene":"Unsaved scene"}</small></div>
      <nav className="header-actions" aria-label="Project and output"><button onClick={()=>void listScenes()} title="Abrir escenas guardadas"><FolderOpen size={17}/><span>Escenas</span></button><button title="Guardar el entorno, personaje y configuración de esta escena" className="save-button" onClick={()=>void saveCloud()} disabled={!ready||!!busy}><Cloud size={17}/><span>Guardar escena</span></button><button aria-label={recording?"Detener y descargar video":"Grabar video de la pantalla limpia"} title="Grabar y descargar video; para guardar movimientos, abre Crear" className={"record-button "+(recording?"recording":"")} onClick={toggleRecord} disabled={!ready}><span className="record-dot"/><span>{recording?Math.floor(recordTime/60)+":"+String(recordTime%60).padStart(2,"0"):"Grabar video"}</span></button><button className="icon-button help-button" onClick={()=>setHelp(true)} aria-label="Studio guide"><CircleHelp size={19}/></button></nav>
    </header>
    <div className="mobile-nav"><button className={mobilePanel==="inputs"?"selected":""} onClick={()=>setMobilePanel("inputs")}><Camera size={16}/>Entradas</button><button className={mobilePanel==="stage"?"selected":""} onClick={()=>setMobilePanel("stage")}><Monitor size={16}/>Personaje</button><button className={mobilePanel==="controls"?"selected":""} onClick={()=>setMobilePanel("controls")}><SlidersHorizontal size={16}/>Controles</button></div>
    <div className={"workspace mobile-"+mobilePanel+(tab==="pose"&&!clean?" is-creating":"")}>
      <aside className="input-panel">
        <div className="panel-title"><span>01 / INPUTS</span><Radio size={15}/></div>
        <section className="input-section">
          <RemoteLink pair={pair} status={remoteStatus} busy={remoteBusy} onConnect={()=>void connectRemote()} onDisconnect={()=>void disconnectRemote()}/>
          <div className="section-heading"><h2><Camera size={16}/>Camera</h2><span className={"status-tag "+(["on","preview","loading"].includes(cameraStatus)?"active":"")}>{pair?"REMOTE":cameraStatus==="on"?"TRACKING":cameraStatus==="loading"||cameraStatus==="preview"?"CAMERA ON":cameraStatus==="starting"?"STARTING":"OFF"}</span></div>
          <div className={"camera-preview "+(config.tracking.mirror?"mirrored":"")}>
            <video ref={video} muted autoPlay playsInline className={cameraStatus==="off"?"hidden-video":""}/><canvas ref={overlay} width={640} height={480} style={{opacity:config.tracking.overlay?1:0}}/>
            {cameraStatus==="off"&&<div className="camera-empty"><ScanFace size={35} strokeWidth={1}/><span>{pair?remoteStatus.connected?"Remote controller connected":"Scan QR to connect":"Your performance starts here"}</span></div>}
            {cameraStatus==="starting"&&<div className="camera-starting"><Loader2 className="spin" size={23}/><span>{cameraProgress}</span></div>}
            {cameraStatus==="loading"&&<div className="camera-loading"><Loader2 className="spin" size={14}/><span>{cameraProgress}</span></div>}
            <span className="camera-corner"/><span className="camera-corner bottom"/>
          </div>
          <button id="studio-camera-start" className={"full-button "+(cameraStatus==="off"?"gold-button":"")} onClick={()=>void toggleCamera()} disabled={!inputReady||!!pair||remoteBusy}>{cameraStatus==="off"?<Camera size={16}/>:<X size={16}/>} {cameraStatus==="off"?"Start camera":cameraStatus==="starting"?"Cancel camera start":"Stop camera"}</button>
          <Choice label="Camera device" value={cameraDevice} onChange={v=>{setCameraDevice(v);if(cameraStatus!=="off")void startCamera(v);}} options={[["auto","Default camera"],...devices.filter(d=>d.kind==="videoinput"&&d.deviceId).map((d,i)=>[d.deviceId,d.label||"Camera "+(i+1)] as [string,string])]}/>
          {isEmbedded&&<a className="standalone-link" href={window.location.href} target="_blank" rel="noopener noreferrer">Open studio in a separate tab</a>}
          {cameraIssue&&<InputIssue issue={cameraIssue} retry={cameraIssue.kind==="tracking"&&tracking.current?.stream?()=>{setCameraIssue(null);tracking.current?.retry(configRef.current.tracking);}:undefined}/>}
          <div className="tracking-state"><span className={"tracking-light "+((cameraStatus==="on"||remoteStatus.camera)&&stats.face?"active":"")}/><span>{pair?remoteStatus.expired?"Remote session ended":!remoteStatus.connected?"Waiting for remote device":stats.face?"Remote face found · live":remoteStatus.camera?"Looking for remote face":"Remote pads ready · camera off":cameraStatus==="starting"?"Waiting for camera":cameraStatus==="loading"?cameraProgress:cameraStatus==="preview"?"Camera ready · tracking unavailable":cameraStatus==="on"&&stats.face?"Face found · tracking live":cameraStatus==="on"?"Looking for your face":"Camera tracking is off"}</span></div>
          <button className="full-button" onClick={()=>void trackHandsAndArms()} disabled={!ready||remoteBusy||!pair&&!inputReady||!pair&&cameraStatus!=="on"&&cameraStatus!=="off"}><Move3D size={15}/>Track my hands & arms</button>
          <details className="workflow-advanced"><summary>Diagnóstico y poses de manos</summary><button className="full-button" onClick={testHands} disabled={!info}>{stats.handTest?"Stop hand rig test":"Test hand rig · 8 seconds"}</button>
          <p className="field-note">Test open hands, fists, pointing and finger spread without a camera. Live tracking uses your actual camera.</p>
          <details className="puppet-local"><summary>Puppet hand poses</summary>{(["left","right"] as const).map(side=><div key={side}><label>{side==="left"?"Left hand":"Right hand"}</label><Choice label={side+" puppet hand"} value={config.puppet[side]} options={[["none","Animation / live"],["open","Open"],["fist","Fist"],["point","Point"],["spread","Finger spread"]]} onChange={v=>{change("puppet",{[side]:v as Config["puppet"]["left"]});change("tracking",{hands:true,handsGain:config.tracking.handsGain||1,wristGain:config.tracking.wristGain||1,fingerGain:config.tracking.fingerGain||1});}}/></div>)}<button className="full-button" onClick={()=>change("puppet",{left:"none",right:"none"})}>Release puppet hands</button></details>
          </details><div className="tracking-options"><Toggle label="Hands & fingers" checked={config.tracking.hands} onChange={v=>{change("tracking",{hands:v});if(v)takeLiveTracking({hands:true});}}/><label className="field-label">Body tracking</label><Choice label="Body tracking" value={config.tracking.pose?config.tracking.bodyMode:"off"} onChange={bodyTracking} options={[["off","Off · face and hands"],["upper","Arms & torso"],["full","Full body · hips to feet"]]}/><Toggle label="Mirror movement" checked={config.tracking.mirror} onChange={v=>change("tracking",{mirror:v})}/><Toggle label="Tracking overlay" checked={config.tracking.overlay} onChange={overlay=>change("tracking",{overlay})}/></div>
          {(config.tracking.pose||config.tracking.hands)&&<div className="body-status" role="status">{config.tracking.hands&&<span className={(cameraStatus==="on"||remoteStatus.camera)&&coverage.hands?"found":""}>{cameraStatus==="on"||remoteStatus.camera?coverage.hands:0}/2 hands</span>}{config.tracking.pose&&<><span className={(cameraStatus==="on"||remoteStatus.camera)&&coverage.arms?"found":""}>Arms {(cameraStatus==="on"||remoteStatus.camera)&&coverage.arms?"found":"waiting"}</span>{config.tracking.bodyMode==="full"&&<span className={(cameraStatus==="on"||remoteStatus.camera)&&coverage.legs?"found":""}>Legs {(cameraStatus==="on"||remoteStatus.camera)&&coverage.legs?"found":"waiting"}</span>}</>}</div>}
          {(config.performance.mode!=="live"||editorEnabled||config.avatar.motionMode==="animation")&&<div className="tracking-owner" role="status"><span>{editorEnabled?"Pose editor":config.performance.mode!=="live"?"Saved "+config.performance.mode:"Animation"} controls the body.</span><button onClick={()=>takeLiveTracking()}>Use live tracking</button></div>}
          {config.tracking.pose&&<p className="field-note body-guide">{config.tracking.bodyMode==="full"?"Step back until hips, knees and feet fit inside the camera. Brief gaps hold your last posture, then ease back to neutral.":"Keep shoulders, elbows and wrists inside the camera for arm motion."}</p>}
          <button className="text-button" onClick={()=>{engine.current?.calibrate();toast.success("Neutral head position calibrated");}} disabled={!ready||!(cameraStatus==="on"||remoteStatus.camera)||!stats.face}><Focus size={14}/>Calibrate neutral</button>
        </section>
        <section className="input-section">
          <div className="section-heading"><h2><Mic size={16}/>Microphone</h2><button className={"small-button "+(micOn?"enabled":"")} onClick={()=>void toggleMic()} disabled={!ready}>{micStarting?"Cancel":micOn?"On":"Enable"}</button></div>
          {micIssue&&<InputIssue issue={micIssue}/>}
          <div className="audio-bars" aria-label={"Microphone level "+Math.round((stats.audio.audio||0)*100)+" percent"}>{Array.from({length:28},(_,i)=><span key={i} className={i/28<(stats.audio.audio||0)?"lit":""}/>)}</div>
          <div className="audio-labels"><span>{micOn?"LIVE INPUT":"NO INPUT"}</span><span>{Math.round((stats.audio.audio||0)*100)}%</span></div>
          {devices.filter(d=>d.kind==="audioinput"&&d.deviceId).length>0&&<Choice label="Microphone device" value={micDevice} onChange={v=>{setMicDevice(v);if(micOn||micStarting){++micAction.current;void engine.current?.stopMic();setMicOn(false);setMicStarting(false);}}} options={[["auto","Default microphone"],...devices.filter(d=>d.kind==="audioinput"&&d.deviceId).map(d=>[d.deviceId,d.label||"Microphone"] as [string,string])]}/>}
          <Range label="Voice sensitivity" value={config.audio.gain} max={10} step={.1} onChange={gain=>change("audio",{gain})}/>
        </section>
        <section className="input-section character-input">
          <div className="section-heading"><h2><Box size={16}/>Character</h2><button className="icon-button" aria-label="Restore original SGX Robot" onClick={resetAvatar} disabled={!ready||!!busy}><RotateCcw size={14}/></button></div>
          <button className="full-button" onClick={()=>{setTab("character");setMobilePanel("controls");}}><Cpu size={15}/>My character library · {config.characters.items.length}</button>
          <button className={"robot-library-button "+(config.avatar.character==="sgx"?"selected":"")} onClick={chooseRobot} disabled={!ready||!!busy} aria-pressed={config.avatar.character==="sgx"}><Cpu size={27}/><span><strong>SGX Robot</strong><small>Energy face · full body & fingers</small></span></button>
          <div className="character-library">{CHARACTERS.map(item=><button key={item.id} className={config.avatar.character===item.id?"selected":""} onClick={()=>void chooseCharacter(item.id)} disabled={!ready||!!busy} aria-pressed={config.avatar.character===item.id}><img src={item.image} alt=""/><strong>{item.id==="highcoon-classic"?"Classic":"TerpSuit"}</strong><small>Face rig · 31 clips</small></button>)}</div>
          <div className="asset-card"><div className="asset-icon"><Box size={23}/></div><div><strong>{info?.name||"Starting renderer"}</strong><small>{info?.faceRig?"Mouthless facial performance rig":info?.builtin?"Built-in performance rig":Math.round((info?.vertices||0)/1000)+"k vertices"}<span>GLB / GLTF</span></small></div></div>
          <button className="full-button upload-button" onClick={()=>avatarInput.current?.click()} disabled={!ready||!!busy}><Upload size={15}/>Load your character</button>
          <button className="text-button" onClick={()=>{setUrlSlot("avatar");setAssetUrl("");}} disabled={!ready}><Cable size={14}/>Load from a direct URL</button>
          <div className="asset-counts"><span><b>{info?.morphs.length||0}</b>morphs</span><span><b>{info?.nodes.filter(n=>n.bone).length||0}</b>bones</span><span><b>{info?.layers.length||0}</b>layers</span></div>
        </section>
        <div className="input-footer"><ShieldCheck size={15}/><p>Camera video stays on its device.<br/>Remote mode sends expressions and pads.</p></div>
      </aside>

      <section className={"stage-column "+(tab==="pose"&&creationTask==="keyframes"&&timelineAdvanced&&!clean?"has-timeline":"")}>
        <div className="stage-topline"><div><span className="stage-label">PERFORMANCE STAGE</span><span className="stage-model">{info?.name||"SGX // 01"}</span></div><div className="stage-top-actions"><button onClick={()=>top("frozen",!config.frozen)} aria-label={config.frozen?"Resume performance":"Pause performance"} title="Space · pause / resume">{config.frozen?<Play size={16}/>:<Pause size={16}/>}</button><button onClick={()=>presetCamera("bust")} aria-label="Reset stage camera" title="Reset camera"><RotateCcw size={16}/></button><button onClick={()=>setOutputSettings(true)} aria-label="Output settings" title="Output settings"><Settings2 size={16}/></button><button onClick={()=>setClean(true)} aria-label="Enter clean output" title="Clean output · Escape to return"><Maximize2 size={17}/></button></div></div>
        <div className={"stage-viewport "+(dragging?"drop-active ":"")+(editorEnabled&&tab==="pose"&&!clean?"is-editing":"")} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);void importAvatar(Array.from(e.dataTransfer.files));}}>
          <canvas ref={canvas} className="render-canvas" aria-label="Realtime 3D avatar performance viewport"/>
          {config.world.type==="transparent"&&<div className="alpha-checker"/>}
          {!ready&&!error&&<div className="stage-loading"><Loader2 size={28} className="spin"/><span>Opening your stage</span></div>}
          {error&&<div className="stage-error" role="alert"><Cpu size={30}/><p>{error}</p></div>}
          {!!busy&&<div className="busy-label"><Loader2 size={15} className="spin"/>{busy}</div>}
          {dragging&&<div className="drop-label"><Upload size={30}/><strong>Drop your character</strong><span>GLB or GLTF + textures · up to 40 MB</span></div>}
          <div className="viewport-top"><div className={"viewport-badge "+(recording?"is-recording":"")}><span/>{recording?"REC":config.frozen?"PAUSED":stats.handTest?"RIG TEST · "+stats.handTest.toUpperCase():config.demo?"DEMO":editorEnabled&&tab==="pose"?"POSE EDITOR":config.performance.mode!=="live"?config.performance.mode.toUpperCase():config.avatar.motionMode==="animation"?"ANIMATION":stats.face||coverage.torso||coverage.hands?"LIVE":"STANDBY"}</div><span className="viewport-resolution">{config.output.resolution}p / {config.output.fps} fps</span></div>
          <div className="viewport-title"><span>SGX</span><small>{config.mode}<br/>AVATAR SYSTEM / 01</small></div>
          <div className="viewport-bottom"><div><span className="tiny-cross">+</span><span>{config.world.type.toUpperCase()}<small>ENVIRONMENT</small></span></div><span className="fps-counter">{stats.fps}<small>FPS</small></span></div>
          <div className="camera-views"><button onClick={()=>presetCamera("portrait")} title="Frame portrait"><ScanFace size={15}/><span>Face</span></button><button onClick={()=>presetCamera("bust")} title="Frame upper body"><Focus size={15}/><span>Bust</span></button><button onClick={()=>presetCamera("full")} title="Frame full body"><Move3D size={15}/><span>Full</span></button></div>
          <button className="clean-return" onClick={()=>setClean(false)}>Return to studio · Esc</button>
        </div>
        <div className="stage-underbar"><span><Move3D size={14}/>{editorEnabled&&tab==="pose"?"Elige una parte y arrastra sus flechas o aros":"Arrastra para girar · scroll para zoom"}</span><div><button onClick={()=>takeLiveTracking()} className={config.performance.mode==="live"&&!editorEnabled&&config.avatar.motionMode!=="animation"?"selected":""} disabled={!ready||!!busy} title="Return body and fingers from pads or poses to camera tracking"><ScanFace size={13}/>Live</button><button onClick={()=>{setTab("pose");setMobilePanel("controls");}} className={tab==="pose"?"selected":""}><Move3D size={13}/>Crear pose / animación</button><button onClick={()=>top("demo",!config.demo)} className={config.demo?"selected":""} aria-pressed={config.demo}><Play size={13}/>{config.demo?"Demo running":"Try demo"}</button><button onClick={()=>{try{engine.current?.openOutput();}catch(e){toast.error(message(e));}}}><Monitor size={14}/>Clean window</button><button onClick={()=>void snapshot()} aria-label="Download PNG frame" title="Snapshot"><Camera size={14}/></button></div></div>
        {creationActivity&&<div className="creation-activity" role="status"><span>{creationActivity}</span><button onClick={()=>{setTab("pose");setMobilePanel("controls");}}>Ver captura</button></div>}
        {tab==="pose"&&creationTask==="keyframes"&&timelineAdvanced&&!clean&&<PoseTimeline engine={engine.current} value={config.performance} onChange={commitPerformance} time={stats.poseTime||0} character={config.characters.selected||undefined} autoKey={autoKey} onAutoKey={setAutoKey} onSave={()=>persistPerformance(configRef.current.performance)}/>}
        <div className="performance-dock"><div className="dock-heading"><span>ACTION DECK</span><span>{config.performance.bank==="moods"?"KEYS 1–6":"KEYS 1–9 / 0"}</span></div><div className="deck-bank-tabs" role="group" aria-label="Action deck bank">{(["moods","A","B","C"] as const).map(bank=><button key={bank} className={config.performance.bank===bank?"selected":""} aria-pressed={config.performance.bank===bank} onClick={()=>{commitPerformance({...configRef.current.performance,bank});if(bank!=="moods")setEditBank(bank);}}>{bank==="moods"?"MOODS":"BANK "+bank}</button>)}<button onClick={()=>{setTab("pads");setMobilePanel("controls");}}><Settings2 size={13}/>Edit deck</button></div>{config.performance.bank==="moods"?<div className="performance-pads">{MODES.map((mode,i)=>{const Icon=modesIcons[i];return <button key={mode} className={"performance-pad mode-"+mode.toLowerCase()+" "+(config.mode===mode?"selected":"")} onClick={()=>top("mode",mode)} aria-pressed={config.mode===mode}><span className="pad-key">0{i+1}</span><Icon size={23} strokeWidth={1.6}/><strong>{mode}</strong></button>;})}</div>:<ActionPads pads={padViews()} bank={config.performance.bank} onPress={id=>triggerPad(id,"press")} onRelease={id=>triggerPad(id,"release")} disabled={!ready||!!busy} onEdit={slot=>{setEditBank(config.performance.bank as ActionPad["bank"]);setEditSlot(slot);setTab("pads");setMobilePanel("controls");}}/>}</div>
        <div className="signal-strip"><span className="strip-label"><Aperture size={14}/>EXPRESSION SIGNALS</span>{[["Mouth","mouthOpen"],["Smile","smile"],["Blink L","blinkLeft"],["Blink R","blinkRight"]].map(([name,key])=><div key={key} className="signal"><span>{name}</span><div><i style={{width:Math.min(100,(stats.signals[key]||0)*100)+"%"}}/></div><b>{Math.round((stats.signals[key]||0)*100)}%</b></div>)}</div>
      </section>

      <aside className="control-panel">
        <div className="panel-title"><span>02 / DIRECTOR</span><SlidersHorizontal size={15}/></div>
        <Tabs value={tab} onValueChange={setTab} className="director-tabs">
          <TabsList className="director-tabs-list primary-director-tabs" aria-label="Qué quieres hacer"><TabsTrigger value="act">Actuar</TabsTrigger><TabsTrigger value={["character","layers","map"].includes(tab)?tab:"character"}>Personaje</TabsTrigger><TabsTrigger value={tab==="pads"?"pads":"pose"}>Crear</TabsTrigger><TabsTrigger value={["world","fx","powers"].includes(tab)?tab:"world"}>Escena</TabsTrigger></TabsList>
          {["character","layers","map"].includes(tab)&&<nav className="director-secondary" aria-label="Opciones del personaje">{[["character","Mis personajes"],["layers","Piezas"],["map","Mapeo avanzado"]].map(([id,label])=><button key={id} aria-pressed={tab===id} className={tab===id?"selected":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>}
          {["pose","pads"].includes(tab)&&<nav className="director-secondary" aria-label="Opciones de creación"><button className={tab==="pose"?"selected":""} aria-pressed={tab==="pose"} onClick={()=>setTab("pose")}>Poses y movimientos</button><button className={tab==="pads"?"selected":""} aria-pressed={tab==="pads"} onClick={()=>setTab("pads")}>Configurar pads</button></nav>}
          {["world","fx","powers"].includes(tab)&&<nav className="director-secondary" aria-label="Opciones de escena">{[["world","Fondo"],["fx","Efectos"],["powers","Powers"]].map(([id,label])=><button key={id} aria-pressed={tab===id} className={tab===id?"selected":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>}
          <div className="director-content">
          <TabsContent value="character"><CharacterLibrary value={config} robot={!!info?.robot} busy={!!busy||!ready} onChange={commitConfig} onSave={saveCharacter} onLoad={p=>void loadSavedCharacter(p)} onDelete={id=>void deleteCharacter(id)} onNew={resetAvatar} onDownload={()=>void downloadRobot()}/></TabsContent>
          <TabsContent value="pose" forceMount hidden={tab!=="pose"}><CreationStudio busy={!!busy} engine={engine.current} value={config.performance} onChange={commitPerformance} enabled={editorEnabled} onEnabled={setEditorEnabled} character={config.characters.selected||undefined} autoKey={autoKey} onAutoKey={setAutoKey} task={creationTask} onTask={setCreationTask} advanced={timelineAdvanced} onAdvanced={v=>{setTimelineAdvanced(v);if(v)setMobilePanel("stage");}} onSave={persistPerformance} onLive={()=>takeLiveTracking().performance} onCaptureLive={()=>takeLiveTracking({hands:true,body:configRef.current.tracking.pose?configRef.current.tracking.bodyMode:"upper"}).performance} cameraActive={cameraStatus==="on"||remoteStatus.camera} onPad={(bank,slot)=>{setEditBank(bank);setEditSlot(slot);setMobilePanel("stage");}} onActivity={setCreationActivity} active={tab==="pose"}/></TabsContent>
          <TabsContent value="pads" forceMount hidden={tab!=="pads"}><PadComposer value={config.performance} onChange={commitPerformance} onSave={persistPerformance} model={engine.current?.poseBinding.model||""} animations={info?.animations||[]} bank={editBank} slot={editSlot} onSelect={(bank,slot)=>{setEditBank(bank);setEditSlot(slot);commitPerformance({...configRef.current.performance,bank});}}/></TabsContent>
          <TabsContent value="act">
            <div className="tab-heading"><h2>Listo para actuar.</h2><p>Elige tu personaje, prende la cámara aquí o en el teléfono y usa los pads debajo del personaje.</p></div><div className="studio-start-actions"><button onClick={()=>setTab("character")}>1 · Elegir personaje</button><button onClick={()=>{setMobilePanel("inputs");document.getElementById("studio-camera-start")?.focus();}}>2 · Cámara / teléfono</button><button onClick={()=>{setTab("pose");setCreationTask("home");}}>3 · Crear poses y movimientos</button></div>
            {!!info?.animations.length&&<div className="control-group"><h3><Play size={15}/>Animation deck</h3><Choice label="Performance driver" value={config.avatar.motionMode} onChange={motionMode=>{if(motionMode!=="animation")takeLiveTracking();change("avatar",{motionMode:motionMode as Config["avatar"]["motionMode"]});}} options={[["tracking","Live · your body"],["animation","Animation · live face + hands"],["hybrid","Hybrid · live arms + animated legs"]]}/><div className="animation-deck">{ANIMATION_PRESETS.filter(p=>info.animations.includes(p.name)).map(p=><button key={p.name} className={stats.animation===p.name?"selected":""} onClick={()=>playAnimation(p.name,p.loop)}><Play size={12}/>{p.label}</button>)}</div><p className="field-note">Playing {stats.animation||"none"}. One-shot gestures return to Idle. All clips are available below.</p></div>}
            {info?.faceRig&&<div className="control-group"><h3><ScanFace size={15}/>Mouthless face</h3><Toggle label="Facial bones" checked={config.face.enabled} onChange={enabled=>change("face",{enabled})}/><Range label="Speech stretch" value={config.face.speech} max={2} onChange={speech=>change("face",{speech})}/><Range label="Squash & stretch" value={config.face.squash} max={2} onChange={squash=>change("face",{squash})}/><Range label="Cheek expression" value={config.face.cheeks} max={2} onChange={cheeks=>change("face",{cheeks})}/><Range label="Brow lift" value={config.face.brows} max={2} onChange={brows=>change("face",{brows})}/><Range label="Eye closure" value={config.face.blink} max={2} onChange={blink=>change("face",{blink})}/><p className="field-note">Start the microphone or camera. Speech shapes the muzzle and head; smiles move the cheeks. Try demo to preview.</p></div>}
            <div className="control-group"><h3><ScanFace size={15}/>Expression intensity</h3>
              <Range label="Head movement" value={config.tracking.head} onChange={head=>change("tracking",{head})}/>
              <Range label="Mouth" value={config.tracking.mouth} onChange={mouth=>change("tracking",{mouth})}/>
              <details className="workflow-advanced"><summary>Ojos, sonrisa y cejas</summary><Range label="Smile" value={config.tracking.smile} onChange={smile=>change("tracking",{smile})}/>
              <Range label="Blink" value={config.tracking.blink} onChange={blink=>change("tracking",{blink})}/>
              <Range label="Eye movement" value={config.tracking.eyes} onChange={eyes=>change("tracking",{eyes})}/>
              <Range label="Eyebrows" value={config.tracking.brows} onChange={brows=>change("tracking",{brows})}/>
              </details><Range label="Smoothing" value={config.tracking.smoothing} max={.95} step={.01} suffix="" onChange={smoothing=>change("tracking",{smoothing})}/>
              <details className="workflow-advanced"><summary>Manos y cuerpo</summary><Range label="Wrist rotation" value={config.tracking.wristGain} onChange={wristGain=>change("tracking",{wristGain})}/>
              <Range label="Finger motion" value={config.tracking.fingerGain} onChange={fingerGain=>change("tracking",{fingerGain})}/>
              <Range label="Hand smoothing" value={config.tracking.handSmoothing} max={.95} step={.01} suffix="" onChange={handSmoothing=>change("tracking",{handSmoothing})}/>
              <Toggle label="Natural hand limits" checked={config.tracking.fingerLimits} onChange={fingerLimits=>change("tracking",{fingerLimits})}/>
              <Range label="Hand motion" value={config.tracking.handsGain} onChange={handsGain=>change("tracking",{handsGain})}/>
              <Range label="Body motion" value={config.tracking.body} onChange={body=>change("tracking",{body})}/>
              <Range label="Arm motion" value={config.tracking.arms} onChange={arms=>change("tracking",{arms})}/>
              <Range label="Leg motion" value={config.tracking.legs} onChange={legs=>change("tracking",{legs})}/>
              <Toggle label="Natural body limits" checked={config.tracking.bodyLimits} onChange={bodyLimits=>change("tracking",{bodyLimits})} note="Keeps elbows, knees and ankles within bounded rotations. Turn off for exaggerated characters."/>
              <Range label="Tracking confidence" value={config.tracking.confidence} min={.1} max={.95} step={.05} suffix="" onChange={confidence=>change("tracking",{confidence})}/>
              <Toggle label="Keep feet grounded" checked={config.tracking.groundFeet} onChange={groundFeet=>change("tracking",{groundFeet})}/><p className="field-note">Adaptive smoothing steadies small movements and follows quick gestures. Brief tracking gaps ease out automatically.</p>
              <p className="field-note">Select Arms & torso or Full body in Inputs. Higher confidence rejects uncertain joints.</p></details>
            </div>
            <div className="control-group"><h3><Mic size={15}/>Voice reactivity</h3><Range label={info?.faceRig?"Voice → face stretch":"Voice → jaw"} value={config.audio.jaw} onChange={jaw=>change("audio",{jaw})}/><Range label="Voice → glow" value={config.audio.glow} onChange={glow=>change("audio",{glow})}/><Range label="Voice → particles" value={config.audio.particles} onChange={particles=>change("audio",{particles})}/><Range label="Noise gate" value={config.audio.gate} max={.2} step={.002} suffix="" onChange={gate=>change("audio",{gate})}/></div>
            <details className="workflow-advanced"><summary>Animaciones del modelo y ajustes del rig</summary><div className="control-group"><h3><Move3D size={15}/>Rig & framing</h3><label className="field-label">Head bone</label><Choice label="Head bone" value={config.avatar.headBone} onChange={headBone=>change("avatar",{headBone})} options={[["auto","Auto-detect head"],...(info?.nodes.filter(n=>n.bone||/head/i.test(n.name)).map(n=>[n.id,n.name] as [string,string])||[])]}/><Range label="Character scale" value={config.avatar.scale} min={.1} onChange={scale=>change("avatar",{scale})}/><Range label="Vertical position" value={config.avatar.y} min={-3} suffix="" onChange={y=>change("avatar",{y})}/><Range label="Facing direction" value={config.avatar.yaw} min={-180} max={180} step={1} suffix="°" onChange={yaw=>change("avatar",{yaw})}/><label className="field-label">Embedded animation</label><Choice label="Embedded animation" value={config.avatar.animation} onChange={animation=>playAnimation(animation,config.avatar.animationLoop)} options={[["none","No body animation"],...(info?.animations.map(n=>[n,n] as [string,string])||[])]}/><Toggle label="Loop selected animation" checked={config.avatar.animationLoop} onChange={animationLoop=>change("avatar",{animationLoop,animationNonce:(config.avatar.animationNonce+1)%1000000000})}/><Range label="Animation blend" value={config.avatar.transition} max={1} step={.05} suffix="s" onChange={transition=>change("avatar",{transition})}/><Range label="Animation speed" value={config.avatar.animationSpeed} onChange={animationSpeed=>change("avatar",{animationSpeed})}/></div>
            <button className="full-button" onClick={()=>{setTab("pose");setCreationTask("home");}} disabled={!ready}><Move3D size={15}/>Crear poses y animaciones</button>
            <div className="control-group rig-editor"><h3><Cable size={15}/>Body & hand bones</h3><p className="field-note">{missingRig.length?"Missing: "+missingRig.map(jointLabel).join(", "):"All 14 core body joints are connected."}</p><p className="field-note">Finger joints: {RIG_ROLES.filter(role=>role.startsWith("left")&&/Proximal|Intermediate|Distal/.test(role)&&(config.avatar.rigMap[role]||info?.rig[role])&&config.avatar.rigMap[role]!=="none").length}/15 left · {RIG_ROLES.filter(role=>role.startsWith("right")&&/Proximal|Intermediate|Distal/.test(role)&&(config.avatar.rigMap[role]||info?.rig[role])&&config.avatar.rigMap[role]!=="none").length}/15 right</p><label className="field-label">Joint to connect</label><Choice label="Rig joint" value={rigJoint} options={RIG_ROLES.map(role=>[role,jointLabel(role)])} onChange={value=>setRigJoint(value as RigRole)}/><label className="field-label">Model bone</label><Choice label="Model bone for selected joint" value={config.avatar.rigMap[rigJoint]||"auto"} options={[["auto","Auto · "+(info?.nodes.find(n=>n.id===info.rig[rigJoint])?.name||"no match")],["none","Disable this joint"],...(info?.nodes.map(n=>[n.id,n.name+" · "+n.id.match(/\[\d+\]$/)?.[0]] as [string,string])||[])]} onChange={assignJoint}/><button className="full-button" onClick={()=>change("avatar",{rigMap:{}})}><Sparkles size={14}/>Auto-detect body & hands</button><p className="field-note">SGX, Mixamo and common humanoid names connect automatically. Assign unusual bone names here; cloud scenes keep your choices.</p></div>
            <button className="full-button" onClick={()=>change("tracking",defaults().tracking)}><RotateCcw size={14}/>Reset tracking controls</button></details>
          </TabsContent>
          <TabsContent value="powers">
            <div className="tab-heading"><h2>Full Spectrum.</h2><p>Eight Riftlands powers. Perform them live.</p></div>
            <Toggle label="Play power animation" checked={powerAnimations} onChange={setPowerAnimations} note="Plays the clip while keeping enabled hand and arm tracking live."/>
            <div className="power-grid">{POWERS.map(p=><button key={p.id} style={{"--power-color":p.color} as CSSProperties} className={config.power.id===p.id?"selected":""} onClick={()=>selectPower(p.id)} disabled={!ready||!!busy} aria-pressed={config.power.id===p.id}><span>{p.code}<small>{p.channel}</small></span><strong>{p.name}</strong><small>{p.role}</small></button>)}</div>
            <div className="power-actions"><button className={"full-button "+(config.power.id==="spectrum"?"gold-button":"")} onClick={()=>selectPower("spectrum")} disabled={!ready||!!busy}><Sparkles size={15}/>Full Spectrum · all colors</button><button className="full-button" onClick={()=>engine.current?.powers.burst(config.power.id)} disabled={!ready||config.power.id==="none"||(stats.overload||0)>0}><Zap size={15}/>{(stats.overload||0)>0?"Overload · "+Math.ceil(stats.overload!)+"s":"Overload · 8 second burst"}</button><button className="text-button" onClick={()=>selectPower("none")}>Clear power effects</button></div>
            <div className="control-group"><h3><Zap size={15}/>Power controls</h3><Range label="Power intensity" value={config.power.intensity} max={2} onChange={intensity=>change("power",{intensity})}/><Range label="Voice → power" value={config.power.reactivity} max={2} onChange={reactivity=>change("power",{reactivity})}/><p className="field-note">Rush trails, recovery rings, carapace shield, bloom petals, reactor orbits, thermal pulses, precision crystals and clarity scans. Effects are included in clean output and recordings.</p></div>
          </TabsContent>
          <TabsContent value="map">
            <div className="tab-heading"><h2>Expression patchbay.</h2><p>Let a smile grow horns. Your rig, your rules.</p></div>
            <div className="mapping-actions"><button onClick={addMapping} disabled={!ready||config.mappings.length>=150}><Plus size={14}/>New route</button><button onClick={()=>top("mappings",autoMappings(info?.morphs||[]))}><Sparkles size={14}/>Auto-map</button></div>
            <div className="mapping-summary"><Cable size={14}/>{config.mappings.filter(m=>m.enabled).length} active routes</div>
            {!config.mappings.length&&<p className="field-note">No matching morphs found. Add a route to any mesh, bone or morph target.</p>}
            {config.mappings.map((m,i)=><div className={"mapping-card "+(!m.enabled?"muted":"")} key={m.id}>
              <div className="mapping-header"><span>ROUTE {String(i+1).padStart(2,"0")}</span><div><Switch checked={m.enabled} onCheckedChange={enabled=>updateMapping(m.id,{enabled})} aria-label={"Enable route "+(i+1)}/><button aria-label={"Remove route "+(i+1)} onClick={()=>top("mappings",config.mappings.filter(n=>n.id!==m.id))}><X size={14}/></button></div></div>
              <label className="field-label">Tracking source</label><Choice label={"Source for route "+(i+1)} value={m.source} options={SOURCES.map(s=>[s,s])} onChange={source=>updateMapping(m.id,{source:source as Mapping["source"]})}/>
              <div className="route-line"><span/><ChevronRight size={13}/><small>DRIVES</small></div>
              <Choice label={"Property for route "+(i+1)} value={m.kind} options={[["morph","Morph target"],["scale","Scale"],["scaleX","Width · X"],["scaleY","Stretch · Y"],["scaleZ","Depth · Z"],["translateX","Move · X"],["translateY","Move · Y"],["translateZ","Move · Z"],["emission","Emission / glow"],["visibility","Visibility"],["rotateX","Rotation X · radians"],["rotateY","Rotation Y · radians"],["rotateZ","Rotation Z · radians"]]} onChange={kind=>updateMapping(m.id,{kind:kind as Mapping["kind"],target:kind==="morph"?(info?.morphs[0]||"missing"):(info?.nodes.find(n=>n.mesh)?.id||"missing")})}/>
              <Choice label={"Target for route "+(i+1)} value={m.target} options={(m.kind==="morph"?info?.morphs.map(n=>[n,n.split("::").at(-1)+" · "+n.split("::")[0]] as [string,string]):info?.nodes.map(n=>[n.id,n.name] as [string,string]))||[["missing","No targets"]]} onChange={target=>updateMapping(m.id,{target})}/>
              <Range label={"Gain · route "+(i+1)} value={m.gain} min={-4} max={4} step={.1} onChange={gain=>updateMapping(m.id,{gain})}/>
              <Range label={"Bias · route "+(i+1)} value={m.offset} min={-1} max={1} step={.05} suffix="" onChange={offset=>updateMapping(m.id,{offset})}/>
            </div>)}
            <div className="control-group"><h3><Play size={15}/>Test a signal</h3><Choice label="Test source" value={manualSource} options={SOURCES.map(s=>[s,s])} onChange={s=>{if(engine.current)engine.current.manual={};setManualSource(s);setManualValue(0);}}/><Range label="Manual value" value={manualValue} max={1} step={.01} suffix="" onChange={v=>{setManualValue(v);if(engine.current)engine.current.manual={[manualSource]:v};}}/><button className="full-button" onClick={()=>{if(engine.current)engine.current.manual={};setManualValue(0);}}>Release test signal</button></div>
            <div className="settings-actions"><button onClick={exportSettings}><Download size={14}/>Export settings</button><button onClick={()=>settingsInput.current?.click()}><Upload size={14}/>Import settings</button></div>
          </TabsContent>
          <TabsContent value="layers">
            <div className="tab-heading"><h2>One rig. Many identities.</h2><p>Switch pieces without leaving your performance.</p></div>
            <div className="control-group"><Toggle label="Wireframe" checked={config.avatar.wireframe} onChange={wireframe=>change("avatar",{wireframe})}/><Toggle label="Tint materials" checked={config.avatar.tint} onChange={tint=>change("avatar",{tint})}/><Color label="Character tint" value={config.avatar.color} onChange={color=>change("avatar",{color})}/></div>
            <div className="layers-heading"><span><Layers3 size={15}/>{info?.layers.length||0} mesh layers</span><button className="text-button" onClick={showAllLayers}>Show all</button></div>
            <input className="text-input layer-search" aria-label="Find a layer" placeholder="Find a layer…" value={layerSearch} onChange={e=>setLayerSearch(e.target.value)}/>
            <div className="layer-list">{info?.layers.filter(n=>n.name.toLowerCase().includes(layerSearch.toLowerCase())).map(n=><label className="layer-row" key={n.id}><Checkbox checked={layerVisible(n.id,n.name)} onCheckedChange={v=>toggleLayer(n.id,n.name,v===true)} aria-label={"Show "+n.name}/><Box size={14}/><span title={n.name}>{n.name}</span><Eye size={13} className={layerVisible(n.id,n.name)?"":"off"}/></label>)}</div>
          </TabsContent>
          <TabsContent value="world">
            <div className="tab-heading"><h2>Build your broadcast space.</h2><p>Change the scene while you perform.</p></div>
            <label className="field-label">Environment</label><Choice label="Environment preset" value={config.world.type} onChange={type=>change("world",{type:type as Config["world"]["type"]})} options={worldOptions}/>
            <div className="control-group"><h3><Globe2 size={15}/>3D environment</h3><div className="environment-file"><Box size={20}/><span>{worldName}</span></div><button className="full-button" disabled={!ready||!!busy} onClick={()=>worldInput.current?.click()}><Upload size={14}/>Load environment GLB / GLTF</button><button className="text-button" onClick={()=>{setUrlSlot("world");setAssetUrl("");}}><Cable size={14}/>Load from URL</button><Range label="Environment scale" value={config.world.scale} min={.1} max={5} onChange={scale=>change("world",{scale})}/><Range label="Environment rotation" value={config.world.rotation} min={-180} max={180} step={1} suffix="°" onChange={rotation=>change("world",{rotation})}/><Range label="Environment height" value={config.world.y} min={-5} max={5} suffix="" onChange={y=>change("world",{y})}/></div>
            <div className="control-group"><h3><ImageIcon size={15}/>Image / video background</h3><div className="environment-file"><ImageIcon size={20}/><span>{mediaName}</span></div><button className="full-button" disabled={!ready||!!busy} onClick={()=>mediaInput.current?.click()}><Upload size={14}/>Choose image or video</button><button className="text-button" onClick={()=>{setUrlSlot("media");setAssetUrl("");}}><Cable size={14}/>Load from URL</button></div>
            <div className="control-group"><h3><Sparkles size={15}/>Light & atmosphere</h3><Color label="Background color" value={config.world.color} onChange={color=>change("world",{color})}/><Color label="Accent light" value={config.world.accent} onChange={accent=>change("world",{accent})}/><Range label="Lighting" value={config.world.light} max={5} suffix="" onChange={light=>change("world",{light})}/><Range label="Fog density" value={config.world.fog} max={.25} step={.005} suffix="" onChange={fog=>change("world",{fog})}/><Range label="Particles" value={config.world.particles} max={1} step={.01} suffix="" onChange={particles=>change("world",{particles})}/><Range label="Ambient motion" value={config.world.speed} onChange={speed=>change("world",{speed})}/></div>
          </TabsContent>
          <TabsContent value="fx">
            <div className="tab-heading"><h2>A little signal interference.</h2><p>Finish the character and the scene together.</p></div>
            {flatOutput&&<p className="output-note">Post effects and particles are bypassed for clean alpha / chroma output.</p>}
            <div className={"control-group "+(flatOutput?"bypassed":"")}>
              <Range label="Bloom" value={config.fx.bloom} max={2} suffix="" onChange={bloom=>change("fx",{bloom})}/>
              <Range label="Chromatic aberration" value={config.fx.chromatic*1000} max={30} step={.5} suffix="" onChange={v=>change("fx",{chromatic:v/1000})}/>
              <Range label="Pixel size" value={config.fx.pixel} min={1} max={16} step={1} suffix=" px" onChange={pixel=>change("fx",{pixel})}/>
              <Range label="Glitch" value={config.fx.glitch} max={1} step={.01} suffix="" onChange={glitch=>change("fx",{glitch})}/>
              <Range label="Vignette" value={config.fx.vignette} max={1} step={.01} suffix="" onChange={vignette=>change("fx",{vignette})}/>
              <Range label="Saturation" value={config.fx.saturation} max={2} suffix="" onChange={saturation=>change("fx",{saturation})}/>
              <Range label="Film grain" value={config.fx.grain} max={.2} step={.005} suffix="" onChange={grain=>change("fx",{grain})}/>
            </div>
            <Range label="Exposure" value={config.fx.exposure} min={.1} max={3} suffix="" onChange={exposure=>change("fx",{exposure})}/>
            <button className="full-button" onClick={()=>change("fx",defaults().fx)}><RotateCcw size={14}/>Reset effects</button>
            <div className="control-group"><h3><Cpu size={15}/>Performance</h3><Choice label="Render quality" value={config.output.quality} options={[["performance","Performance · bloom bypassed"],["balanced","Balanced"],["ultra","Ultra"]]} onChange={quality=>change("output",{quality:quality as Config["output"]["quality"]})}/><Range label="Tracking frequency" value={config.tracking.rate} min={10} max={30} step={1} suffix=" Hz" onChange={rate=>change("tracking",{rate})}/><p className="field-note">Reduce tracking frequency, resolution or body tracking when the scene is heavy.</p></div>
          </TabsContent>
          </div>
        </Tabs>
        <div className="director-footer"><span><Cpu size={13}/>{cameraStatus==="on"?"MediaPipe · "+Math.round(stats.inference)+" ms":"On-device tracking"}</span><span>WEBGL 2</span></div>
      </aside>
    </div>
    <footer className="studio-footer"><span>TALES, TERPS & TECH <b> / </b> REALTIME PERFORMANCE LAB</span><span>SPACE TO PAUSE <b>·</b> ESC TO RETURN</span></footer>
    <input hidden type="file" ref={avatarInput} multiple accept=".glb,.gltf,.bin,.png,.jpg,.jpeg,.webp,.ktx2" onChange={e=>{void importAvatar(Array.from(e.target.files||[]));e.target.value="";}}/>
    <input hidden type="file" ref={worldInput} multiple accept=".glb,.gltf,.bin,.png,.jpg,.jpeg,.webp" onChange={e=>{void importWorld(Array.from(e.target.files||[]));e.target.value="";}}/>
    <input hidden type="file" ref={mediaInput} accept="image/png,image/jpeg,image/webp,image/avif,video/mp4,video/webm,video/quicktime" onChange={e=>{if(e.target.files?.[0])void importMedia(e.target.files[0]);e.target.value="";}}/>
    <input hidden type="file" ref={settingsInput} accept=".json" onChange={e=>{if(e.target.files?.[0])void importSettings(e.target.files[0]);e.target.value="";}}/>
    <Dialog open={!!urlSlot} onOpenChange={v=>{if(!v)setUrlSlot(null);}}><DialogContent className="sgx-dialog"><DialogTitle>Load {urlSlot==="avatar"?"a character":urlSlot==="world"?"a 3D environment":"a background"}</DialogTitle><DialogDescription>Use a direct HTTPS file link that allows cross-origin loading. For GLTF with separate files, use the upload control.</DialogDescription><input className="text-input" aria-label="Direct asset URL" type="url" placeholder={urlSlot==="media"?"https://…/background.png":"https://…/character.glb"} value={assetUrl} onChange={e=>setAssetUrl(e.target.value)}/><button className="full-button gold-button" onClick={()=>void loadUrl()} disabled={!assetUrl||!!busy}>{busy?<Loader2 className="spin" size={16}/>:<Upload size={16}/>}Load asset</button></DialogContent></Dialog>
    <Dialog open={outputSettings} onOpenChange={setOutputSettings}><DialogContent className="sgx-dialog"><DialogTitle>Broadcast output</DialogTitle><DialogDescription>Recording and snapshots capture the rendered stage, without interface or camera preview.</DialogDescription><label className="field-label">Canvas resolution</label><Choice label="Output resolution" value={config.output.resolution} options={[["720","1280 × 720"],["1080","1920 × 1080"],["1440","2560 × 1440"]]} onChange={resolution=>change("output",{resolution:resolution as Config["output"]["resolution"]})}/><label className="field-label">Recording frame rate</label><Choice label="Recording frame rate" value={config.output.fps} options={[["24","24 fps"],["30","30 fps"],["60","60 fps"]]} onChange={fps=>change("output",{fps:fps as Config["output"]["fps"]})}/><label className="field-label">Background</label><Choice label="Output background" value={config.world.type} options={worldOptions} onChange={type=>change("world",{type:type as Config["world"]["type"]})}/><p className="output-note">OBS: capture the clean window and use Chroma green with a Chroma Key filter. Transparent canvas and PNG preserve alpha; recorded video alpha depends on your browser. Enable the mic before recording to include your voice.</p><button className="full-button" onClick={()=>{try{engine.current?.openOutput();setOutputSettings(false);}catch(e){toast.error(message(e));}}}><Monitor size={16}/>Open clean output window</button></DialogContent></Dialog>
    <Dialog open={cloudOpen} onOpenChange={setCloudOpen}><DialogContent className="sgx-dialog cloud-dialog"><DialogTitle><Cloud size={20}/>Your cloud scenes</DialogTitle><DialogDescription>Models, backgrounds, layer states and expression mappings travel together.</DialogDescription>{cloudError?<p className="output-note" role="alert">{cloudError}</p>:!scenes.length?<p className="empty-scenes">No scenes yet. Name your performance and press Save.</p>:<div className="scene-list">{scenes.map(s=><div className="scene-row" key={s.id}><Box size={24}/><div><strong>{s.name}</strong><small>{new Date(s.updated).toLocaleDateString()}</small></div><button onClick={()=>void openScene(s.id)} disabled={!!busy}>{busy?"Loading…":"Open"}</button><button className="icon-button" aria-label={"Delete "+s.name} onClick={()=>setDeleteScene(s)}><Trash2 size={16}/></button></div>)}</div>}<button className="full-button" onClick={()=>{setSceneId(null);setSavedAt("");cloudAssets.current={avatar:null,environment:null,media:null};setCloudOpen(false);toast("Your next save will create a new cloud scene.");}}><Plus size={15}/>Save current performance as a new scene</button></DialogContent></Dialog>
    <AlertDialog open={!!deleteScene} onOpenChange={v=>{if(!v)setDeleteScene(null);}}><AlertDialogContent className="sgx-dialog"><AlertDialogTitle>Delete {deleteScene?.name}?</AlertDialogTitle><AlertDialogDescription>This removes the saved cloud scene and assets that are not used by another scene. The current stage stays open.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep scene</AlertDialogCancel><AlertDialogAction onClick={()=>void removeScene()}>Delete scene</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Dialog open={help} onOpenChange={setHelp}><DialogContent className="sgx-dialog help-dialog"><DialogTitle>Your character. Your performance.</DialogTitle><DialogDescription>SGX vTuber Engine · Tales, Terps & Tech</DialogDescription><div className="guide-steps"><p><b>01</b><span><strong>Elige el personaje y prende la cámara.</strong> Usa la cámara de esta pantalla o conecta el teléfono en Entradas. Puedes actuar con los pads sin cámara.</span></p><p><b>02</b><span><strong>Guarda una pose.</strong> Abre Crear → Guardar una pose. Mueve las partes en 3D o copia tu postura con la cámara. Ponle nombre y pulsa Guardar pose. Después, Poner en un pad.</span></p><p><b>03</b><span><strong>Crea un movimiento.</strong> En Crear, elige Grabar mis movimientos para actuar y capturar, o Animar paso a paso para añadir posturas. Prueba la animación y guárdala. El timeline completo está en opciones avanzadas.</span></p><p><b>04</b><span><strong>Actúa y graba video.</strong> Los pads reproducen tus acciones en esta pantalla y en el teléfono. Grabar video descarga tu actuación. Guardar escena conserva también el fondo y los ajustes. Tus poses y movimientos ya se guardan desde Crear.</span></p></div><p className="output-note">GLB / GLTF · Draco / Meshopt · PNG / JPG / WebP / AVIF · MP4 / WebM. Use PNG/JPG textures inside compressed models; KTX2 and VRM-specific spring bones are not supported in this version.</p><div className="tracking-check"><button className="full-button" onClick={()=>void runTrackingCheck()} disabled={checkingTracking||cameraStatus!=="off"}>{checkingTracking?<Loader2 className="spin" size={15}/>:<ScanFace size={15}/>}Check tracking engine</button><p className="field-note">Checks enabled tracking models without opening the camera. Stop the camera before running this check.</p>{trackingCheck&&<p role="status">{trackingCheck}</p>}{trackingCheckIssue&&<InputIssue issue={trackingCheckIssue}/>}</div><div className="settings-actions"><button onClick={exportSettings}><FileJson size={15}/>Export settings</button><button onClick={()=>{settingsInput.current?.click();setHelp(false);}}><Upload size={15}/>Import settings</button><button onClick={()=>{void engine.current?.modelBlob().then(blob=>download(blob,"SGX-character.glb")).catch(e=>toast.error(message(e)));}}><Download size={15}/>Download character GLB</button></div></DialogContent></Dialog>
  </main>;
}
