import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {realpath,rm} from 'node:fs/promises';
import * as T from 'three';
const {build}=createRequire(await realpath(new URL('../node_modules/wrangler/package.json',import.meta.url)))('esbuild'),out=new URL('../.sites-runtime/robot-check.mjs',import.meta.url).pathname;
await build({stdin:{contents:['state','avatar','robot','rig','rig-roles','loader'].map(p=>`export * from "./lib/engine/${p}.ts";`).join(''),resolveDir:process.cwd(),loader:'ts'},bundle:true,platform:'node',format:'esm',packages:'external',outfile:out});
globalThis.FileReader=class{result=null;onload=null;onloadend=null;readAsArrayBuffer(blob){blob.arrayBuffer().then(data=>{this.result=data;this.onload?.({target:this});this.onloadend?.({target:this});});}readAsDataURL(blob){blob.arrayBuffer().then(data=>{this.result='data:'+blob.type+';base64,'+Buffer.from(data).toString('base64');this.onload?.({target:this});this.onloadend?.({target:this});});}};
const E=await import(out);let root,loaded;
try{
 root=E.createAvatar();const nodes=[];root.traverse(n=>nodes.push({id:n.name,name:n.name,bone:!!n.isBone}));const bones=nodes.filter(n=>n.bone),rig=E.autoRigMapping(nodes);
 assert.equal(bones.length,57);assert.equal(new Set(bones.map(n=>n.name)).size,57);assert.equal(E.RIG_ROLES.filter(r=>!rig[r]).length,0,'every body and finger role must connect');assert.equal(bones.filter(n=>/Proximal|Intermediate|Distal/.test(n.name)).length,30);
 for(const name of ['neck','head','eyeLeft','eyeRight','jaw','energyMouth','browLeft','browRight'])assert.ok(root.getObjectByName(name)?.isBone,name);
 const config=E.defaults(),old={...config};delete old.robot;assert.deepEqual(E.parseConfig(old).robot,E.robotDefaults());assert.throws(()=>E.parseConfig({...config,robot:{...config.robot,pose:{head:[999,0,0]}}}));
 config.robot={...config.robot,armor:'#803fff',eyes:'#ff6600',mouth:'#33ff77',headScale:1.2,eyeWidth:1.4,mouthWidth:1.25,helmet:false,pose:{LeftIndexProximal:[50,0,0],RightUpperArm:[0,0,-25]}};
 const native=new E.RobotRig(root);assert.ok(native.available);native.apply(config,{mouthOpen:.6});assert.equal(root.getObjectByName('EYE_L').material.emissive.getHexString(),'ff6600');assert.equal(root.getObjectByName('MOUTH').material.emissive.getHexString(),'33ff77');assert.equal(root.getObjectByName('HELMET').visible,false);assert.ok(root.getObjectByName('jaw').position.y<-.19);assert.ok(root.getObjectByName('LeftIndexProximal').rotation.x>.8);
 root.updateMatrixWorld(true);const expected=new Map();root.traverse(m=>{if(m.isMesh)expected.set(m.name,{point:new T.Vector3().fromBufferAttribute(m.geometry.attributes.position,0).applyMatrix4(m.matrixWorld),material:m.material.color.getHexString()});});
 const blob=await E.exportGLB(root);loaded=await E.loadFiles([new File([blob],'SGX-Robot.glb',{type:'model/gltf-binary'})]);loaded.root.updateMatrixWorld(true);
 const importedBones=[],skins=[];loaded.root.traverse(o=>{if(o.isBone)importedBones.push(o);if(o.isSkinnedMesh)skins.push(o);});assert.equal(importedBones.length,57,'exported GLB must contain actual joints');assert.equal(skins.length,75,'each rigid robot piece must be weighted to its joint');
 for(const skin of skins){skin.skeleton.update();const point=new T.Vector3().fromBufferAttribute(skin.geometry.attributes.position,0);skin.applyBoneTransform(0,point).applyMatrix4(skin.matrixWorld);const original=expected.get(skin.name);assert.ok(point.distanceTo(original.point)<.00001,skin.name+' preserves customized geometry in GLB');assert.equal(skin.material.color.getHexString(),original.material);}
 const look=E.robotLookFromModel(loaded.root);assert.ok(look);assert.equal(look.armor,'#803fff');assert.equal(look.eyes,'#ff6600');assert.equal(look.mouth,'#33ff77');assert.equal(look.headScale,1,'baked proportions must not be applied twice');assert.equal(look.helmet,false);assert.deepEqual(look.pose,{});
 const importedConfig=E.defaults();importedConfig.robot=look;new E.RobotRig(loaded.root).apply(importedConfig,{});assert.equal(loaded.root.getObjectByName('HELMET').visible,false);assert.equal(loaded.root.getObjectByName('MOUTH').material.emissive.getHexString(),'33ff77');
 const finger=loaded.root.getObjectByName('LeftIndexProximal'),mesh=loaded.root.getObjectByName('FINGER_Left_Index');loaded.root.updateMatrixWorld(true);mesh.skeleton.update();const vertices=()=>Array.from({length:mesh.geometry.attributes.position.count},(_,i)=>mesh.applyBoneTransform(i,new T.Vector3().fromBufferAttribute(mesh.geometry.attributes.position,i)).applyMatrix4(mesh.matrixWorld));const before=vertices();finger.rotateX(.7);loaded.root.updateMatrixWorld(true);mesh.skeleton.update();assert.ok(Math.max(...vertices().map((v,i)=>v.distanceTo(before[i])))>.025,'moving exported finger bone deforms its real mesh');
 const eye=loaded.root.getObjectByName('EYE_L'),mouth=loaded.root.getObjectByName('MOUTH');assert.ok('Blink_L' in eye.morphTargetDictionary);assert.ok('Mouth_Open' in mouth.morphTargetDictionary);
 console.log(JSON.stringify({verified:true,bones:57,fingerBones:30,bodyRoles:E.RIG_ROLES.length,skinnedParts:skins.length,checks:['original energy face','full body and fingers','facial joints','old scene migration','bounded bone poses','independent energy colors','custom proportions and layers','GLB actual joints and skin weights','roundtrip vertex positions and palette','import without double scaling','real exported finger motion','eye and mouth morphs']}));
}finally{if(root)E.disposeTree(root);if(loaded)E.disposeTree(loaded.root);await rm(out,{force:true});}
